/**
 * `apps/web/wrangler.deploy.toml` — one instance's wrangler config, RENDERED from the committed
 * template (`apps/web/wrangler.toml`) and never committed. The two committed tomls stay neutral
 * templates (the parity test and local dev read them unchanged); everything instance-specific comes
 * from `launch.deploy.env` (the answers) and `.launch/state.json` (the ids provisioning created).
 *
 * Pure: `renderDeployToml(template, input)` → text. What it changes, and nothing else:
 *
 *   - a GENERATED header, so nobody edits the output by hand
 *   - `name` and every account-scoped name (queue producer + consumer, R2 buckets — `BACKUP_BUCKET`
 *     shares FILES' bucket — workflows) re-prefixed from the template's name to `LAUNCH_NAME`;
 *     with the default `launch` they are byte-identical to the template's
 *   - `workers_dev = false`: the instance is served on its own host only
 *   - `routes`: Launch's host as a Worker custom domain, plus the zone route `*.<domain>/*` that
 *     sends every other subdomain (apps' previews, coding-session previews) to the Worker — an app's
 *     own custom domain wins over the route, as any custom domain does
 *   - `[vars]` APP_URL, EMAIL_FROM, SESSION_PREVIEW_URL, DATABASE_DRIVER = "neon"
 *   - with both R2 keys in the instance file, coding-session workspace backups on: `[vars]`
 *     SESSION_WORKSPACE_BACKUP = "presigned", BACKUP_BUCKET_NAME (the bucket `BACKUP_BUCKET` names)
 *     and CLOUDFLARE_ACCOUNT_ID (a `<PLACEHOLDER>` until an account id is known); without them
 *     backups stay off, as the template has them
 *   - the RATE_LIMIT_KV id (a `<PLACEHOLDER>` until `cloudflare` has created it)
 *   - every installed plugin's declarations (D31): bindings named from `LAUNCH_NAME`, crons,
 *     worker-first prefixes, non-secret vars, Durable Object migrations — the same mapping
 *     `pluginBindingBlocks` gives the parity test
 *
 * The edits go through `patch-toml.ts` (byte-preserving, comments kept) where it has one; the
 * rest are anchored line rewrites here.
 */
import {
  type BindingBlock,
  patchToml,
  readTomlString,
  TomlPatchError,
  tomlPlaceholders,
} from './patch-toml'
import {
  type PluginResources,
  pluginBindingBlocks,
  pluginDeclarations,
  pluginMigrationBlocks,
} from './plugin-resources'

export interface RenderInput {
  /** LAUNCH_NAME — the Worker name and the account-scoped prefix. */
  name: string
  /** LAUNCH_DOMAIN — the zone. */
  domain: string
  /** LAUNCH_HOST — Launch's own custom domain. */
  host: string
  /** `"<App name> <noreply@<EMAIL_DOMAIN>>"`. */
  emailFrom: string
  /** binding → KV namespace id; a binding with no id keeps its placeholder. */
  kvIds?: Record<string, string>
  plugins?: PluginResources[]
  /** Set = workspace backups on (`workspaceBackupState`); its account id, when one is known. */
  workspaceBackup?: { accountId?: string }
}

/** The Worker secrets a presigned workspace backup signs its R2 URLs with. */
export const BACKUP_KEY_NAMES = ['R2_ACCESS_KEY_ID', 'R2_SECRET_ACCESS_KEY'] as const
export const ACCOUNT_ID_PLACEHOLDER = '<CLOUDFLARE_ACCOUNT_ID>'

/**
 * Whether the render turns coding-session workspace backups on: both R2 keys set, nothing else
 * (`has` answers by name — a value is never read here). `why` is the one line `check` prints.
 */
export function workspaceBackupState(has: (name: string) => boolean): {
  on: boolean
  why: string
} {
  const set = BACKUP_KEY_NAMES.filter(has)
  const unset = BACKUP_KEY_NAMES.filter(n => !has(n))
  if (!unset.length)
    return {
      on: true,
      why: `${set.join(' + ')} set — render adds SESSION_WORKSPACE_BACKUP = "presigned", BACKUP_BUCKET_NAME, CLOUDFLARE_ACCOUNT_ID`,
    }
  if (set.length) return { on: false, why: `${set.join(', ')} set but ${unset.join(', ')} not` }
  return { on: false, why: `${unset.join(', ')} not set` }
}

/** The bucket the `BACKUP_BUCKET` binding names (FILES' bucket — the SDK writes under backups/). */
export function backupBucketName(text: string): string {
  const m = /^\s*binding\s*=\s*"BACKUP_BUCKET"\s*\n\s*bucket_name\s*=\s*"([^"]+)"/m.exec(text)
  if (!m) throw new TomlPatchError('no `[[r2_buckets]]` block binding BACKUP_BUCKET found')
  return m[1]
}

export const GENERATED_HEADER = [
  '# GENERATED by `pnpm provision render` from wrangler.toml + launch.deploy.env + .launch/state.json.',
  '# Do not edit: change the template or the instance file and re-render. Git-ignored on purpose —',
  '# it names one instance (its host, ids and account-scoped resources). docs/DEPLOYMENT.md.',
  '',
].join('\n')

const escapeRe = (s: string) => s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')

/**
 * Re-prefix every ACTIVE (uncommented) `queue` / `bucket_name` / `dead_letter_queue` / `name` line
 * whose value is the template's name or starts with `<template>-`. Comment lines are left alone;
 * Durable Object `name = "SESSION_SANDBOX"` lines never match (they do not carry the prefix).
 */
export function reprefixNames(text: string, from: string, to: string): string {
  if (from === to) return text
  const re = new RegExp(
    `^(\\s*(?:name|queue|bucket_name|dead_letter_queue)\\s*=\\s*")${escapeRe(from)}((?:-[^"]*)?")`,
    'gm'
  )
  return text.replace(re, `$1${to}$2`)
}

/** Replace the active or commented `routes = [...]` line with the instance's two routes. */
export function setRoutes(text: string, host: string, domain: string): string {
  const line = `routes = [\n  { pattern = "${host}", custom_domain = true },\n  { pattern = "*.${domain}/*", zone_name = "${domain}" },\n]`
  const active = /^routes\s*=\s*\[[\s\S]*?\]\s*$/m.exec(text)
  if (active)
    return text.slice(0, active.index) + line + text.slice(active.index + active[0].length)
  const commented = /^#\s*routes\s*=\s*\[[^\n]*\]/m.exec(text)
  if (!commented) throw new TomlPatchError('no `routes = [...]` line (active or commented) found')
  return text.slice(0, commented.index) + line + text.slice(commented.index + commented[0].length)
}

/** `workers_dev = false` right after `name = …`, replacing any existing (or commented) setting. */
export function setWorkersDevOff(text: string): string {
  const existing = /^#?\s*workers_dev\s*=[^\n]*$/m.exec(text)
  if (existing)
    return `${text.slice(0, existing.index)}workers_dev = false${text.slice(existing.index + existing[0].length)}`
  const nameLine = /^name\s*=\s*"[^"]*"[^\n]*\n/m.exec(text)
  if (!nameLine) throw new TomlPatchError('no `name = "…"` line found')
  const at = nameLine.index + nameLine[0].length
  return `${text.slice(0, at)}workers_dev = false   # served on its custom domain only\n${text.slice(at)}`
}

/** Set a `[vars]` key, inserting it when the template has none. */
function setVar(text: string, key: string, value: string): string {
  const re = new RegExp(`^(${key}\\s*=\\s*")([^"]*)(")`, 'm')
  if (re.test(text)) return text.replace(re, `$1${value.replace(/\$/g, '$$$$')}$3`)
  return patchToml(text, { vars: [{ key, value }] })
}

export function renderDeployToml(template: string, input: RenderInput): string {
  const from = readTomlString(template, 'name')
  if (!from) throw new TomlPatchError('the template has no `name = "…"`')
  let out = template
  out = reprefixNames(out, from, input.name)
  out = setWorkersDevOff(out)
  out = setRoutes(out, input.host, input.domain)
  out = setVar(out, 'APP_URL', `https://${input.host}`)
  out = setVar(out, 'EMAIL_FROM', input.emailFrom)
  out = setVar(out, 'SESSION_PREVIEW_URL', `https://{label}.${input.domain}`)
  out = patchToml(out, { databaseDriver: 'neon' })
  if (input.workspaceBackup) {
    out = setVar(out, 'SESSION_WORKSPACE_BACKUP', 'presigned')
    out = setVar(out, 'BACKUP_BUCKET_NAME', backupBucketName(out))
    out = setVar(
      out,
      'CLOUDFLARE_ACCOUNT_ID',
      input.workspaceBackup.accountId || ACCOUNT_ID_PLACEHOLDER
    )
  }

  const kvIds = input.kvIds ?? {}
  if (kvIds.RATE_LIMIT_KV) out = patchToml(out, { kvId: kvIds.RATE_LIMIT_KV, force: true })

  const plugins = input.plugins ?? []
  if (plugins.length) {
    const { crons, apiPrefixes, vars } = pluginDeclarations(plugins)
    const bindings: BindingBlock[] = pluginBindingBlocks(input.name, plugins, 'production').map(
      b => (b.type === 'kv' && kvIds[b.binding] ? { ...b, id: kvIds[b.binding] } : b)
    )
    out = patchToml(out, {
      bindings,
      migrations: pluginMigrationBlocks(plugins),
      crons,
      workerFirstPrefixes: apiPrefixes,
      vars: vars.filter(v => !v.secret).map(v => ({ key: v.key, value: v.example ?? '' })),
      force: true,
    })
  }
  return GENERATED_HEADER + out
}

/** The `<PLACEHOLDER>`s a rendered file still carries — `deploy` refuses any. */
export const renderedPlaceholders = tomlPlaceholders
