/**
 * How a Rocketflare checkout (kit 0.15) is brought up inside a session's sandbox — the
 * `devBootstrap` of spec/02, as Launch drives it (plan §3b, S7). Everything here goes through the
 * `SandboxPort`, so it runs the same against a real container and a `FakeSandbox`.
 *
 * `sessionBootstrap(ctx)` — the `bootstrap` step (and a `prepare` run's migrate + seed):
 *
 * 0. The allow-list gains EXACTLY the database's Neon endpoint (`sessionDbEgressHosts`): the
 *    container has no TCP out, so the app reaches its branch over the neon driver — the `Pool`'s
 *    WebSocket to the endpoint, the Worker's HTTP queries to the region's `api.` host.
 * 1. `pnpm install --frozen-lockfile --prefer-offline` — from the image's warm store (S7: ~5 s,
 *    against ~17 s cold).
 * 2. `node scripts/bootstrap.mjs --db-url "$LAUNCH_DB_URL" --driver neon --offline --no-dev
 *    --no-open --no-plugins --yes` (with `NOT_ROOT_PRELOAD`: the kit refuses root, and a sandbox
 *    runs as root; plus `--no-install` and the kit's own skip and root variables on a checkout
 *    whose bootstrap takes them — {@link bootstrapInvocation}) — the kit's own first run against a database it
 *    does not own:
 *    `.dev.vars` from the example with the URL and a fresh encryption key, migrate, seed
 *    (idempotent; `SEED_ALLOW_REMOTE=1` under `--db-url`). **`--no-plugins`**: a session never changes the app's plugin set — the repo's
 *    committed plugins are what it runs. The ports go in the ENVIRONMENT (`DEV_UI_PORT=5173`,
 *    `DEV_API_PORT=8787`, `DEV_ALLOWED_HOSTS=.<preview suffix>`), which `scripts/lib/dev-ports.mjs`
 *    reads before `.dev.vars`, with `DATABASE_DRIVER=neon` (the scripts read the driver from the
 *    environment) — and on a laptop `GOGC=off` (see `SessionDevEnv.emulated`).
 * 3. The dev-server keys go INTO `apps/web/.dev.vars` afterwards — `APP_URL=<preview origin>` (the
 *    Worker builds its CORS / CSRF allow-list and redirects from it and cannot read the process
 *    environment), the ports, `DATABASE_DRIVER=neon` and an empty `NEON_LOCAL_PROXY` (never a
 *    proxy: the branch's endpoint is reached directly, on a laptop too).
 *
 * **A session never changes a tracked file for its dev setup.** `--offline` (no Cloudflare login in
 * a sandbox) makes the kit comment `[ai]` out of both wrangler tomls IN PLACE; the preload keeps
 * those writes from happening (`BOOTSTRAP_KEEP_ENV`), and the dev server runs from a git-ignored
 * `apps/web/wrangler.session.toml` (`[ai]` off) that wrangler's own redirect file points
 * `wrangler dev` at (`SESSION_WRANGLER_SCRIPT`, run by the dev start). `worker-configuration.d.ts`
 * is never generated by the setup; `wrangler types` ignores the redirect, so the gate's typecheck
 * keeps `AI`. What an
 * earlier Launch committed is put back on a resume (`healDevSetup`), and a checkpoint refuses to
 * commit the toggle (`checkpoint.ts`, the dev-setup guard).
 *
 * `startDevServer(sandbox, dev)` — the `dev` step: the kit's dev server (`node --import <session
 * config script> apps/web/scripts/dev-server.mjs --start`, what `pnpm dev` runs, with the session's
 * wrangler config written by the same node first; `pnpm dev` itself when the script is missing —
 * `DEV_START_COMMAND`) in the background (its pid and output in `DEV_PID_FILE` / `DEV_LOG_FILE`),
 * then `:8787/api/health` 2xx and, after it, a TCP connect to `:5173` (`DEV_READY_PROBE`) — one
 * in-container wait per short chunk, failing at once if the dev server exits; then the UI's `/`
 * warmed in the background. Every dev step's node shares a compile cache inside the workspace
 * (`NODE_COMPILE_CACHE_DIR`), and Miniflare's `cf.json` fetch is off.
 *
 * The install and the kit bootstrap each run as a BACKGROUND command, polled
 * (`background-command.ts`) — never one blocking `exec`: the Sandbox SDK queues every other call
 * behind a running exec and the sandbox host's binding drops a long one. A step retry attaches to
 * the run an earlier attempt left going; the running step's detail follows the kit's `✔ n/10`
 * lines (`onProgress`); past `BOOTSTRAP_TIMEOUTS` the process group is killed.
 *
 * A failed command's error carries the last `ERROR_TAIL_LINES` of its output, the database URI
 * scrubbed (`tailOf`), and the install and bootstrap run under one `flock` (`serialised`), so a
 * re-run step attempt never races an earlier one's `pnpm install`.
 *
 * **Never port 3000**: it is the Sandbox SDK's own control server inside every sandbox (S7
 * finding 3); `tests/config/session-bootstrap.test.ts` pins that nothing here names it.
 *
 * The database URI is the ONE credential a session's container holds — for its own throwaway
 * branch (spec/07) — and it travels only as the `LAUNCH_DB_URL` environment variable of the
 * bootstrap command and in the checkout's git-ignored `.dev.vars`; never in an argument, a step
 * result or an event.
 */
import {
  BackgroundCommandTimeoutError,
  formatDuration,
  runInBackground,
} from './background-command'
import { sessionDbEgressHosts } from './db/neon-session-db'
import { type SandboxPort, SandboxProcessExitedError, sessionAllowedHosts } from './ports'

/** Bump with `LABEL dev.rocketflare.launch.session-image` in `containers/session/Dockerfile`. */
export const SESSION_IMAGE_VERSION = 'session-6'
/** The kit tag whose pnpm store the image carries (`ARG KIT_TAG`). */
export const SESSION_KIT_TAG = '0.16.0'

/** The app's Vite UI — the preview port. */
export const SESSION_UI_PORT = 5173
/** The app's `wrangler dev` API, behind Vite's `/api` proxy. */
export const SESSION_API_PORT = 8787

/**
 * Where the checkout lives in the container — THE one definition: the repo step clones here, the
 * turn runs Claude Code here (`SESSION_WORKDIR`, `claude-stream.ts`), and the checkpoint and the
 * ship gate run git and the gate here (`SESSION_REPO_DIR`, `checkpoint.ts`).
 */
export const SESSION_WORKSPACE = '/workspace/app'
/** `$HOME` in the container: the image runs everything as root, so Claude Code's state is here. */
export const SESSION_HOME = '/root'
/** Launch's own helper files, outside the checkout. */
export const SESSION_LAUNCH_DIR = '/workspace/.launch'
/**
 * Claude Code's transcripts for a session run in `SESSION_WORKSPACE` (`~/.claude/projects/<cwd with
 * / as ->/<session id>.jsonl`) — what a checkpoint copies to R2 and a resume puts back.
 */
export const CLAUDE_PROJECT_DIR = `${SESSION_HOME}/.claude/projects/${SESSION_WORKSPACE.replace(/[^A-Za-z0-9]/g, '-')}`

export const claudeTranscriptPath = (claudeSessionId: string): string =>
  `${CLAUDE_PROJECT_DIR}/${claudeSessionId}.jsonl`

/**
 * How long each phase may take before the step fails (then cleanup runs). The install and the
 * bootstrap are killed at theirs (`runInBackground`).
 */
export const BOOTSTRAP_TIMEOUTS = {
  installMs: 10 * 60_000,
  bootstrapMs: 15 * 60_000,
  uiMs: 3 * 60_000,
  apiMs: 3 * 60_000,
} as const

/** What the dev stack needs to know about where it is served from. */
export interface SessionDevEnv {
  /** `https://5173-<short>-<token>.clewro.com` — the preview origin, or null when previews are off. */
  previewOrigin: string | null
  /** `.clewro.com` — the suffix every preview host shares (Vite's `allowedHosts`), or null. */
  previewHostSuffix: string | null
  /**
   * The container runs on a laptop (`APP_ENV=development`: `wrangler dev`'s Docker, whichever
   * `SESSION_BACKEND`), where the amd64-only sandbox image runs under emulation (QEMU on an ARM
   * Mac) and Go binaries — esbuild, under `tsx`, Vite and wrangler — crash in their garbage
   * collector ("The service was stopped", "found pointer to free object", a garbled
   * `Invalid version` mid-transform). Measured: `GOGC=off` keeps them alive; `GOMAXPROCS=1` and
   * `GODEBUG=asyncpreemptoff=1` do not. `GOMEMLIMIT` bounds the cost — the collector only runs
   * near it. Deployed containers are native amd64 and get neither.
   */
  emulated?: boolean
}

/**
 * How much the kit's vitest time limits scale in a session container (`TEST_LATENCY_FACTOR`, kit
 * rocketflare-dev/rocketflare#62): a container has a fraction of a laptop's CPU — under emulation
 * on an ARM Mac in `wrangler dev` — so a test an agent runs BY HAND, outside the ship gate, timed
 * out at vitest's 5 s (`plugin-skills.test.ts`'s end-to-end upgrade took 7.3 s) and the agent went
 * after a failure that was not one. 4 is the factor the kit already gives the `neon` driver
 * (20 s per test). The kit takes the LARGER of this and its own target factor, so the gate's 12
 * stands; a kit older than the variable ignores it.
 */
export const SESSION_TEST_LATENCY_FACTOR = '4'

/** Variables every process in the container gets — the turn's agent and every dev step. */
export function sessionSharedEnv(): Record<string, string> {
  return { TEST_LATENCY_FACTOR: SESSION_TEST_LATENCY_FACTOR }
}

/**
 * Node's on-disk compile cache (`NODE_COMPILE_CACHE`, Node 22.1+; the image runs 24) for every
 * dev step's node — pnpm, the kit's scripts, wrangler, Vite. INSIDE the workspace, so a workspace
 * backup (and a prebuild — `PREBUILD_EXCLUDES` keeps it: V8 code cache keyed on each file's path
 * and content, nothing session-specific) carries it to the next container, where wrangler and Vite
 * start without compiling their bundles again (measured -11 % on the dev start). Node writes it
 * when a process EXITS through JS — a SIGTERM the process handles, never a SIGKILL — which is why a
 * backup stops the dev server politely first (`stopDevServerGracefully`).
 */
export const NODE_COMPILE_CACHE_DIR = `${SESSION_WORKSPACE}/node_modules/.cache/node-compile-cache`

/**
 * Command-level variables every step shares: no credential, no telemetry, the ports, and the neon
 * driver — the container has no TCP out, so the kit's scripts (which read `DATABASE_DRIVER` from
 * the environment before `.dev.vars`) must speak HTTPS/WebSocket to the branch.
 *
 * `CLOUDFLARE_CF_FETCH_ENABLED=false`: Miniflare otherwise fetches `request.cf` from
 * `https://workers.cloudflare.com/cf.json` (3 s timeout) on a start without a cached copy — a host
 * the session's allow-list does not carry, so `wrangler dev` waited the 3 s out. The app gets
 * Miniflare's built-in placeholder `cf` object instead. Plus Node's compile cache
 * ({@link NODE_COMPILE_CACHE_DIR}).
 */
export function sessionProcessEnv(dev: SessionDevEnv): Record<string, string> {
  return {
    ...sessionSharedEnv(),
    CI: '1',
    WRANGLER_SEND_METRICS: 'false',
    CLOUDFLARE_CF_FETCH_ENABLED: 'false',
    NODE_COMPILE_CACHE: NODE_COMPILE_CACHE_DIR,
    DATABASE_DRIVER: 'neon',
    DEV_UI_PORT: String(SESSION_UI_PORT),
    DEV_API_PORT: String(SESSION_API_PORT),
    ...(dev.previewHostSuffix ? { DEV_ALLOWED_HOSTS: dev.previewHostSuffix } : {}),
    ...(dev.emulated ? { GOGC: 'off', GOMEMLIMIT: '1536MiB' } : {}),
  }
}

/**
 * The keys `apps/web/.dev.vars` must carry for `pnpm dev` to serve the preview — and the neon
 * driver, straight to the branch: `NEON_LOCAL_PROXY` is emptied, so nothing routes it anywhere else.
 */
export function sessionDevVars(dev: SessionDevEnv): Record<string, string> {
  return {
    DATABASE_DRIVER: 'neon',
    NEON_LOCAL_PROXY: '',
    DEV_UI_PORT: String(SESSION_UI_PORT),
    DEV_API_PORT: String(SESSION_API_PORT),
    APP_URL: dev.previewOrigin ?? `http://localhost:${SESSION_UI_PORT}`,
    ...(dev.previewHostSuffix ? { DEV_ALLOWED_HOSTS: dev.previewHostSuffix } : {}),
  }
}

/** The preview origin's host suffix: `https://{label}.clewro.com` → `.clewro.com`. */
export function previewHostSuffix(template: string | undefined): string | null {
  if (!template) return null
  const host = template.replace(/^[a-z]+:\/\//i, '').split('/')[0] ?? ''
  const suffix = host.slice('{label}'.length).replace(/:\d+$/, '')
  return host.startsWith('{label}') && suffix.startsWith('.') ? suffix : null
}

export const INSTALL_COMMAND = 'pnpm install --frozen-lockfile --prefer-offline --reporter=silent'

/**
 * The kit's bootstrap refuses to run as root (kit 0.15: `os.userInfo().uid === 0` → exit 3), and a
 * sandbox's commands run as root — the container is the isolation boundary, not the user. This
 * preload tells the bootstrap's ONE check otherwise; everything it runs (pnpm, migrate, seed)
 * still runs as root. Kit 0.17.4 added the explicit opt-out (`ROCKETFLARE_ALLOW_ROOT=1`), which
 * {@link bootstrapInvocation} sets when the checkout's bootstrap takes it; the stand-in stays for older ones.
 *
 * **It also makes the bootstrap's database work lighter.** The kit's bootstrap has no flag to skip
 * its migrate, seed or database check, and reaches each ONLY as a `pnpm <script>` child
 * (`spawn('pnpm', ['db:migrate'])`, `['seed', …]`, `['web', 'db:check']`), which the preload
 * rewrites — the `spawn` binding the bootstrap imported is swapped through
 * `syncBuiltinESMExports`, before the bootstrap loads:
 * - For each part named in `LAUNCH_BOOTSTRAP_SKIP` (`BOOTSTRAP_SKIP_ENV`) it answers that child
 *   with a one-line `node -e` that prints what the kit's step checks for ("Migrations applied")
 *   and exits 0. `sessionBootstrap` always skips three ({@link ALWAYS_SKIPPED}): `db-check` (the
 *   branch was just made through Neon's API, and the migrator fails loudly if it cannot connect),
 *   `install` (the kit's step 2 `pnpm install --prefer-offline`, a second install right after
 *   Launch's own — the kit then only checks the exit code and that
 *   `apps/web/node_modules/.bin/wrangler` exists, which it still does) and `whoami` (step 8's
 *   `pnpm web exec wrangler whoami`: a sandbox never has a Cloudflare login, and the kit reads
 *   "logged in" only from "You are logged in with" in the output — the stand-in's
 *   "You are not authenticated" takes `--offline`'s not-logged-in branch, `[ai]` off, exactly as
 *   the real call did, without starting wrangler). Measured locally the two cost 8-12 s of the
 *   bootstrap. Verified against the kit's `scripts/bootstrap.mjs` and `parseWhoami`, identical
 *   from 0.15.0 through 0.17.3. **From kit 0.17.4 the kit leaves all of these out itself**
 *   (`--no-install`, `ROCKETFLARE_BOOTSTRAP_SKIP`, a `--offline` with no whoami —
 *   {@link bootstrapInvocation}), and the stand-ins are only the fallback for an older kit.
 * - `pnpm db:migrate` that is NOT skipped runs the kit's migrator ALONE
 *   (`pnpm web exec dotenv -e .dev.vars -- tsx scripts/migrate.ts`), without the kit's `db-roles`
 *   before and after it: the RLS role those make (the app's `<snake>_app`) is on `dev` already,
 *   held by `session_owner` WITH ADMIN (`NeonSessionDb`'s `ensureAppRole`), and its grants matter only under `TENANT_SCOPE_MODE=enforce`, which a
 *   session never runs. Each of those scripts opens its OWN database WebSocket through the
 *   container's egress interception, and on real Cloudflare containers one of the later ones
 *   hung (docs/plans/sandbox-session-issues.md): a prepare now opens two (migrate, seed), a
 *   session whose migrations changed one, and a resume none.
 *
 * **It keeps the bootstrap off the app's tracked files.** `--offline` makes the kit comment the
 * `[ai]` block out of BOTH wrangler tomls in place (`setAiBlocks` → `writeFileSync`), and a
 * checkpoint commits the whole tree — so the toggle once rode a session's PR, which would have
 * removed Workers AI from the app's production. Every path in `LAUNCH_BOOTSTRAP_KEEP`
 * (`BOOTSTRAP_KEEP_ENV`, absolute, comma-separated — `SESSION_DEV_TRACKED_FILES`) is written by no
 * `writeFileSync` of the bootstrap's: the call returns without writing. The session's dev server
 * runs from its own git-ignored copy instead (`SESSION_WRANGLER_SCRIPT`, run by the dev start).
 *
 * Everything else (`.dev.vars`, the install) runs as the kit wrote it.
 */
export const NOT_ROOT_PRELOAD = `${SESSION_LAUNCH_DIR}/bootstrap-in-sandbox.mjs`
export const NOT_ROOT_PRELOAD_SCRIPT = `import cp from 'node:child_process'
import fs from 'node:fs'
import { syncBuiltinESMExports } from 'node:module'
import os from 'node:os'
import path from 'node:path'
const userInfo = os.userInfo
os.userInfo = options => ({ ...userInfo(options), uid: 1000 })
const skip = new Set((process.env.LAUNCH_BOOTSTRAP_SKIP || '').split(',').filter(Boolean))
const stand = [
  ['install', a => a[0] === 'install', 'Already up to date (install skipped by Launch: it ran just before the bootstrap)'],
  ['whoami', a => a[0] === 'web' && a[1] === 'exec' && a[2] === 'wrangler' && a[3] === 'whoami', 'You are not authenticated. Please run wrangler login. (whoami skipped by Launch: a sandbox has no Cloudflare login)'],
  ['seed', a => a[0] === 'seed', 'seed skipped by Launch: a resume never re-seeds'],
  ['migrate', a => a[0] === 'db:migrate', 'Migrations applied (skipped by Launch: unchanged since the last bootstrap)'],
  ['db-check', a => a[0] === 'web' && a[1] === 'db:check', 'db:check skipped by Launch: the branch was made through the Neon API'],
]
const instead = {
  'db:migrate': ['web', 'exec', 'dotenv', '-e', '.dev.vars', '--', 'tsx', 'scripts/migrate.ts'],
}
const keep = new Set((process.env.LAUNCH_BOOTSTRAP_KEEP || '').split(',').filter(Boolean).map(f => path.resolve(f)))
const writeFileSync = fs.writeFileSync
fs.writeFileSync = function (file, ...rest) {
  if (typeof file === 'string' && keep.has(path.resolve(file))) return
  return writeFileSync.call(this, file, ...rest)
}
const spawn = cp.spawn
cp.spawn = function (cmd, args, opts) {
  const list = Array.isArray(args) ? args : []
  const hit = cmd === 'pnpm' ? stand.find(([part, match]) => skip.has(part) && match(list)) : undefined
  if (hit) {
    return spawn.call(this, process.execPath, ['-e', 'console.log(' + JSON.stringify(hit[2]) + ')'], opts)
  }
  const script = cmd === 'pnpm' ? list[0] : undefined
  if (script && Object.hasOwn(instead, script)) {
    return spawn.call(this, cmd, [...instead[script], ...list.slice(1)], opts)
  }
  return spawn.apply(this, arguments)
}
syncBuiltinESMExports()
`

/** What a bootstrap may leave out (`BOOTSTRAP_SKIP_ENV`, see {@link NOT_ROOT_PRELOAD}). */
export type BootstrapSkip = 'seed' | 'migrate' | 'db-check' | 'install' | 'whoami'
/** What EVERY session bootstrap leaves out, a first boot's too (see {@link NOT_ROOT_PRELOAD}). */
export const ALWAYS_SKIPPED: readonly BootstrapSkip[] = ['db-check', 'install', 'whoami']
/** The environment variable the preload reads: comma-separated {@link BootstrapSkip}s. */
export const BOOTSTRAP_SKIP_ENV = 'LAUNCH_BOOTSTRAP_SKIP'
/** The environment variable the preload reads: absolute paths the bootstrap must never write. */
export const BOOTSTRAP_KEEP_ENV = 'LAUNCH_BOOTSTRAP_KEEP'

// ---- the kit's own bootstrap flags (kit 0.17.4+) ------------------------------------------------

/**
 * The first kit whose bootstrap leaves out what a sandbox does not need by itself
 * (rocketflare-dev/rocketflare 0.17.4, `scripts/bootstrap.mjs` + `scripts/lib/bootstrap-lib.mjs`):
 * `--offline` no longer runs `wrangler whoami` (step 8 comments `[ai]` out without asking),
 * `--no-install` leaves step 2's `pnpm install` out (it still checks
 * `apps/web/node_modules/.bin/wrangler`, exit 3 without it), `ROCKETFLARE_BOOTSTRAP_SKIP` names
 * steps 1-8 to leave out (each prints `✔ n/10 <name> skipped (ROCKETFLARE_BOOTSTRAP_SKIP)`; an
 * unknown name is exit 2) and `ROCKETFLARE_ALLOW_ROOT=1` lifts the root refusal. An OLDER bootstrap
 * refuses `--no-install` as an unknown option, so the CHECKOUT's own parser decides
 * ({@link kitBootstrapFlagsIn}) — never a version number: a Launch-style copy's
 * `launch.plugins.json` `kitVersion` is its plugin-API level, not the age of its bootstrap.
 */
export const KIT_BOOTSTRAP_LIB = 'scripts/lib/bootstrap-lib.mjs'
/** What {@link KIT_BOOTSTRAP_LIB} must contain for the kit's flags to be used: all three. */
export const KIT_BOOTSTRAP_FLAG_MARKERS = [
  "'--no-install'",
  'ROCKETFLARE_BOOTSTRAP_SKIP',
  'ROCKETFLARE_ALLOW_ROOT',
] as const
/** The kit's own variable: comma-separated step names (`BOOTSTRAP_SKIPPABLE_STEPS`) to leave out. */
export const KIT_BOOTSTRAP_SKIP_ENV = 'ROCKETFLARE_BOOTSTRAP_SKIP'
/** The kit's own variable: `1` lets the bootstrap run as uid 0. */
export const KIT_ALLOW_ROOT_ENV = 'ROCKETFLARE_ALLOW_ROOT'

/**
 * A {@link BootstrapSkip} as the kit's step name, for the parts the kit's own skip covers whole:
 * `db-check` is ALL of step 4 under `--db-url` (`stepExternalDatabase`: a `db:check` and nothing
 * else). `install` is the `--no-install` flag instead, and `whoami` needs nothing — `--offline`
 * never asks.
 */
const KIT_STEP_OF: Partial<Record<BootstrapSkip, string>> = {
  'db-check': 'database',
  migrate: 'migrate',
  seed: 'seed',
}

/** What the bootstrap phase runs: its command line and the variables that shape it (no secret). */
export interface BootstrapInvocation {
  command: string
  env: Record<string, string>
  /** True when the kit's own flags do the leaving out; false when the preload's stand-ins do. */
  kitFlags: boolean
}

/**
 * How the kit bootstrap is told what to leave out (`skip` plus {@link ALWAYS_SKIPPED}), by what
 * the checkout's bootstrap understands ({@link checkoutTakesKitFlags}):
 *
 * - **it takes the kit's flags (0.17.4+)** — `--no-install`, {@link KIT_BOOTSTRAP_SKIP_ENV}
 *   with the steps {@link KIT_STEP_OF} names, {@link KIT_ALLOW_ROOT_ENV}`=1`, and `whoami` left to
 *   `--offline`. The preload stays: it still runs a `db:migrate` that is not skipped as the
 *   migrator alone and keeps the tracked files unwritten (`BOOTSTRAP_KEEP_ENV`); its uid stand-in
 *   is then redundant, and its `pnpm` stand-ins never match (no {@link BOOTSTRAP_SKIP_ENV}).
 * - **it does not, or its parser could not be read** — the preload's stand-ins, as before.
 */
export function bootstrapInvocation(
  kitFlags: boolean,
  skip: readonly BootstrapSkip[] = []
): BootstrapInvocation {
  const skipped = new Set<BootstrapSkip>([...skip, ...ALWAYS_SKIPPED])
  if (!kitFlags) {
    return {
      command: BOOTSTRAP_COMMAND,
      env: { [BOOTSTRAP_SKIP_ENV]: [...skipped].join(',') },
      kitFlags: false,
    }
  }
  const steps = [...skipped].map(part => KIT_STEP_OF[part]).filter((s): s is string => !!s)
  return {
    command: `${BOOTSTRAP_COMMAND}${skipped.has('install') ? ' --no-install' : ''}`,
    env: {
      [KIT_ALLOW_ROOT_ENV]: '1',
      ...(steps.length > 0 ? { [KIT_BOOTSTRAP_SKIP_ENV]: steps.join(',') } : {}),
    },
    kitFlags: true,
  }
}

/** Does this `scripts/lib/bootstrap-lib.mjs` text parse the kit's flags? Pure. */
export function kitBootstrapFlagsIn(libText: string | null): boolean {
  return libText !== null && KIT_BOOTSTRAP_FLAG_MARKERS.every(marker => libText.includes(marker))
}

/**
 * Whether the checkout's bootstrap takes the kit's own flags — FEATURE-detected from its argument
 * parser ({@link KIT_BOOTSTRAP_LIB}, one read), at every bootstrap, so a kit-upgrade session's
 * resume follows its branch. The parser is what refuses an unknown option, so it is the file that
 * decides; a bootstrap whose `bootstrap.mjs` lags its parser still works (it only runs the step it
 * was told to leave out). A read that fails, or no such file, keeps the stand-ins, which work on
 * any kit.
 */
export async function checkoutTakesKitFlags(sandbox: SandboxPort): Promise<boolean> {
  const text = await sandbox.readFile(`${SESSION_WORKSPACE}/${KIT_BOOTSTRAP_LIB}`).catch(() => null)
  return kitBootstrapFlagsIn(text)
}

// ---- the dev setup never touches a tracked file ------------------------------------------------

/** The app's wrangler config — tracked; its `[ai]` block is what the kit's `--offline` toggles. */
export const WRANGLER_TOML = 'apps/web/wrangler.toml'
/** The staging twin, toggled with it by the kit (`setAiBlocks`). */
export const WRANGLER_STAGING_TOML = 'apps/web/wrangler.staging.toml'
/** Generated from the toml by `wrangler types` (the kit's `pnpm typecheck`) — tracked. */
export const WORKER_TYPES = 'apps/web/worker-configuration.d.ts'
/**
 * The tracked files a session's dev setup once changed (the `[ai]` toggle and the types generated
 * from it). A session never writes them for its setup: only the agent does, as part of its work.
 */
export const SESSION_DEV_TRACKED_FILES = [
  WRANGLER_TOML,
  WRANGLER_STAGING_TOML,
  WORKER_TYPES,
] as const

/**
 * The session's own wrangler config: `wrangler.toml` with the `[ai]` block commented out (Workers
 * AI needs a Cloudflare login, which a sandbox never has). Beside the toml, so every relative path
 * in it (`main`, `[assets]`) resolves the same; git-ignored through `.git/info/exclude`.
 */
export const SESSION_WRANGLER_CONFIG = 'apps/web/wrangler.session.toml'
/**
 * Wrangler's own redirect (`.wrangler/deploy/config.json`, `{ "configPath": … }`): `wrangler dev`
 * reads the config it names instead of `wrangler.toml` — so the kit's `pnpm dev` runs on
 * {@link SESSION_WRANGLER_CONFIG} with no flag and no kit change. `wrangler types` does NOT follow
 * it, so the kit's `pnpm typecheck` still generates `worker-configuration.d.ts` from the tracked
 * toml (measured on wrangler 4.127: dev prints "Using redirected Wrangler configuration.").
 * `.wrangler/` is git-ignored by the kit, and by the exclude file too.
 */
export const WRANGLER_REDIRECT = 'apps/web/.wrangler/deploy/config.json'
/** What `.git/info/exclude` carries for the dev setup (anchored at the checkout's root). */
export const SESSION_DEV_EXCLUDES = [`/${SESSION_WRANGLER_CONFIG}`, '/apps/web/.wrangler/'] as const

/**
 * The kit's `[ai]` block toggle (kit 0.15 `scripts/lib/bootstrap-lib.mjs` `aiBlockState` /
 * `toggleAiBlock`), as JavaScript for the scripts below: `[ai]` live is `on`, the kit's commented
 * form (`# [ai]` then `# `-prefixed lines) is `off`.
 */
const AI_TOGGLE_JS = `const AI_ON = /^\\[ai\\]\\s*$/
const AI_OFF = /^# \\[ai\\]\\s*$/
const SECTION = /^\\s*\\[/
const aiState = text => {
  for (const line of text.split('\\n')) {
    if (AI_ON.test(line)) return 'on'
    if (AI_OFF.test(line)) return 'off'
  }
  return 'absent'
}
const toggleAi = (text, mode) => {
  const state = aiState(text)
  if (state === 'absent' || state === mode) return text
  const lines = text.split('\\n')
  const start = lines.findIndex(line => (mode === 'off' ? AI_ON : AI_OFF).test(line))
  let end = start + 1
  if (mode === 'off') while (end < lines.length && lines[end].trim() !== '' && !SECTION.test(lines[end])) end += 1
  else while (end < lines.length && lines[end].startsWith('# ')) end += 1
  const block = lines.slice(start, end).map(line => (mode === 'off' ? '# ' + line : line.slice(2)))
  return [...lines.slice(0, start), ...block, ...lines.slice(end)].join('\\n')
}`

/**
 * Writes {@link SESSION_WRANGLER_CONFIG} from the checkout's CURRENT `wrangler.toml` (the agent's
 * own edits included) with `[ai]` off, points wrangler's redirect at it, and makes sure the exclude
 * file names both. Run from the checkout's root. Prints `session-config ai=<on|off|absent>` — the
 * tracked toml's state, which it never writes.
 */
export const SESSION_WRANGLER_SCRIPT = `import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import path from 'node:path'
${AI_TOGGLE_JS}
const toml = ${JSON.stringify(WRANGLER_TOML)}
if (!existsSync(toml)) {
  console.error('no ' + toml + ' in the checkout')
  process.exit(1)
}
const text = readFileSync(toml, 'utf8')
const header = '# Generated by Launch for this coding session from wrangler.toml, with [ai] off (no Cloudflare\\n# login in a sandbox). Git-ignored (.git/info/exclude); \`wrangler dev\` reads it through\\n# .wrangler/deploy/config.json. Never commit it: edit wrangler.toml instead.\\n'
writeFileSync(${JSON.stringify(SESSION_WRANGLER_CONFIG)}, header + toggleAi(text, 'off'))
const redirect = ${JSON.stringify(WRANGLER_REDIRECT)}
mkdirSync(path.dirname(redirect), { recursive: true })
const target = path.relative(path.dirname(redirect), ${JSON.stringify(SESSION_WRANGLER_CONFIG)})
writeFileSync(redirect, JSON.stringify({ configPath: target }) + '\\n')
const exclude = '.git/info/exclude'
mkdirSync(path.dirname(exclude), { recursive: true })
let ex = existsSync(exclude) ? readFileSync(exclude, 'utf8') : ''
for (const line of ${JSON.stringify(SESSION_DEV_EXCLUDES)}) {
  if (!ex.split('\\n').includes(line)) ex += (ex === '' || ex.endsWith('\\n') ? '' : '\\n') + line + '\\n'
}
writeFileSync(exclude, ex)
console.log('session-config ai=' + aiState(text))
`

/**
 * Puts back what an EARLIER Launch's dev setup left in a session's branch (before the dev config
 * moved out of the tracked files, every checkpoint committed the kit's offline toggle): given the
 * session's base commit (argv[2]), run from the checkout's root —
 *
 * - a wrangler toml whose `[ai]` is `off` where the base's is `on` gets the block back (the rest of
 *   the file — the agent's own edits — is left as it is);
 * - `worker-configuration.d.ts` is the base's again when it differs from it ONLY by the `AI: Ai;`
 *   line and wrangler's generated header (any other difference is the agent's: the ship gate's
 *   `pnpm typecheck` regenerates it from the healed toml, and the ship commits that).
 *
 * The working tree only; the next checkpoint commits it. Prints `healed\t<path>` per file.
 */
export const DEV_SETUP_HEAL_SCRIPT = `import { execFileSync } from 'node:child_process'
import { existsSync, readFileSync, writeFileSync } from 'node:fs'
${AI_TOGGLE_JS}
const base = process.argv[2]
if (!base) process.exit(0)
const atBase = file => {
  try {
    return execFileSync('git', ['show', base + ':' + file], { encoding: 'utf8', maxBuffer: 256 * 1024 * 1024, stdio: ['ignore', 'pipe', 'ignore'] })
  } catch {
    return null
  }
}
for (const toml of ${JSON.stringify([WRANGLER_TOML, WRANGLER_STAGING_TOML])}) {
  const was = atBase(toml)
  if (was === null || !existsSync(toml)) continue
  const now = readFileSync(toml, 'utf8')
  if (aiState(was) === 'on' && aiState(now) === 'off') {
    writeFileSync(toml, toggleAi(now, 'on'))
    console.log('healed\\t' + toml)
  }
}
const types = ${JSON.stringify(WORKER_TYPES)}
const AI_LINE = /^\\s*AI: Ai;\\s*$/m
const was = atBase(types)
if (was !== null && existsSync(types)) {
  const now = readFileSync(types, 'utf8')
  const norm = text => text.split('\\n').filter(line => !/^\\/\\/ Generated by Wrangler/.test(line) && !/^\\s*AI: Ai;\\s*$/.test(line)).join('\\n')
  if (AI_LINE.test(was) && !AI_LINE.test(now) && norm(was) === norm(now)) {
    writeFileSync(types, was)
    console.log('healed\\t' + types)
  }
}
`

const HEAL_SCRIPT_PATH = `${SESSION_LAUNCH_DIR}/heal-dev-setup.mjs`
const SESSION_WRANGLER_SCRIPT_PATH = `${SESSION_LAUNCH_DIR}/session-wrangler.mjs`

/**
 * {@link DEV_SETUP_HEAL_SCRIPT} in the checkout against `baseSha`: the files it put back. A failure
 * is not fatal (the checkpoint's guard still stands between a toggle and a commit): it answers [].
 */
export async function healDevSetup(
  sandbox: SandboxPort,
  baseSha: string | null
): Promise<string[]> {
  if (!baseSha || !/^[0-9a-f]{7,64}$/.test(baseSha)) return []
  await sandbox.writeFile(HEAL_SCRIPT_PATH, DEV_SETUP_HEAL_SCRIPT)
  const result = await sandbox.exec(`node ${HEAL_SCRIPT_PATH} ${baseSha}`, {
    cwd: SESSION_WORKSPACE,
    timeoutMs: 60_000,
  })
  if (result.exitCode !== 0) return []
  return [...result.stdout.matchAll(/^healed\t(.+)$/gm)].map(m => m[1] ?? '')
}

/**
 * Put {@link SESSION_WRANGLER_SCRIPT} where the dev start runs it: the dev server's own config,
 * from the current `wrangler.toml`, made by every dev-server start, so an agent's edit to the toml
 * reaches the next start. It runs INSIDE the dev server's start ({@link DEV_START_COMMAND}: a
 * `--import` preload of the kit's supervisor), not as an `exec` of its own — one RPC and one node
 * start fewer. A failure there (no `wrangler.toml`) exits the dev server with the reason in its
 * log, which the dev step reports.
 */
export async function writeSessionWranglerScript(sandbox: SandboxPort): Promise<void> {
  await sandbox.writeFile(SESSION_WRANGLER_SCRIPT_PATH, SESSION_WRANGLER_SCRIPT)
}

/** Where the kit keeps its SQL migrations — what a resume's migrate decision hashes. */
export const MIGRATIONS_DIR = 'apps/web/migrations'

/**
 * One sha256 over every file under {@link MIGRATIONS_DIR} (path and content, sorted), printed as
 * `migrations=<hex>`: equal hashes mean the session's database already has these migrations.
 */
export const MIGRATIONS_HASH_COMMAND = `cd ${SESSION_WORKSPACE} && h=$( (find ${MIGRATIONS_DIR} -type f -print0 2>/dev/null | sort -z | xargs -0 -r sha256sum) | sha256sum | cut -c1-64) && echo "migrations=$h"`

/** The migrations hash of the checkout in `sandbox`, or null when it could not be computed. */
export async function migrationsHash(sandbox: SandboxPort): Promise<string | null> {
  const result = await sandbox.exec(MIGRATIONS_HASH_COMMAND, { timeoutMs: 60_000 })
  if (result.exitCode !== 0) return null
  return /migrations=([0-9a-f]{64})/.exec(result.stdout)?.[1] ?? null
}

export const BOOTSTRAP_COMMAND = `node --import ${NOT_ROOT_PRELOAD} scripts/bootstrap.mjs --db-url "$LAUNCH_DB_URL" --driver neon --offline --no-dev --no-open --no-plugins --yes`

/** The kit's dev-stack supervisor — what `pnpm dev` runs (root → `@<app>/web dev` → this). */
export const DEV_SERVER_SCRIPT = 'apps/web/scripts/dev-server.mjs'
/**
 * The dev server, run DIRECTLY: the kit's `pnpm dev` is `pnpm --silent --filter @<app>/web dev`,
 * which is `node scripts/dev-server.mjs --start` in `apps/web` (kit 0.15.0 through 0.17.3) — two
 * pnpm startups (1-3 s in a container) for nothing. The script resolves its own directory from
 * `import.meta.url`, spawns `wrangler` and `vite` by absolute path from `apps/web/node_modules/.bin`
 * with `cwd` `apps/web`, and reads its ports from the environment then `.dev.vars` — nothing pnpm's
 * environment adds. Its `--stop` (`pnpm dev:stop`) still finds it: its process match is
 * `dev-server.mjs --start` with a cwd in the checkout.
 *
 * The session's wrangler config is written by the same node process, before the supervisor loads:
 * {@link SESSION_WRANGLER_SCRIPT} as a `--import` preload (synchronous writes; a missing toml exits
 * 1). A `--import` on the command line is not inherited by the supervisor's children.
 */
export const DEV_COMMAND = `node --import ${SESSION_WRANGLER_SCRIPT_PATH} ${DEV_SERVER_SCRIPT} --start`
/** What runs when the checkout has no {@link DEV_SERVER_SCRIPT} (an app that moved it). */
export const DEV_FALLBACK_COMMAND = 'pnpm dev'

/** The dev server's pid (`startDevServer`) — what the port wait checks is still alive. */
export const DEV_PID_FILE = `${SESSION_LAUNCH_DIR}/dev.pid`
/** The dev server's output, for the error when it dies before its ports answer. */
export const DEV_LOG_FILE = `${SESSION_LAUNCH_DIR}/dev.log`
/**
 * The dev server as the dev step starts it — {@link DEV_COMMAND}, or {@link DEV_FALLBACK_COMMAND}
 * when the script is not there (the session config written by a `node` of its own first): its pid
 * recorded (the shell `exec`s into it, so `$$` IS the dev server) and its output kept in a file.
 */
export const DEV_START_COMMAND = `mkdir -p ${SESSION_LAUNCH_DIR} && echo $$ > ${DEV_PID_FILE} && if [ -f ${DEV_SERVER_SCRIPT} ]; then exec ${DEV_COMMAND} > ${DEV_LOG_FILE} 2>&1; else node ${SESSION_WRANGLER_SCRIPT_PATH} > ${DEV_LOG_FILE} 2>&1 && exec ${DEV_FALLBACK_COMMAND} >> ${DEV_LOG_FILE} 2>&1; fi`

/**
 * Started in the background once the dev stack is ready: one GET of the UI's `/`, so Vite's
 * transform of the UI graph (the preview's first paint) is under way before the person's browser
 * asks. Nothing waits on it and nothing reads its result.
 */
export const DEV_WARM_COMMAND = `curl -s -o /dev/null -m 120 http://127.0.0.1:${SESSION_UI_PORT}/ >/dev/null 2>&1; exit 0`

/**
 * The biggest files a dev start reads first, under the checkout (globs: pnpm's virtual store names
 * carry versions and platforms). After a FUSE restore (a workspace backup or a prebuild in
 * `presigned` mode: s3fs → squashfuse → an overlay) every first read of them pages in from R2;
 * {@link PREREAD_COMMAND} reads them through once while the bootstrap runs.
 */
export const DEV_HOT_PATHS = [
  'node_modules/.pnpm/@esbuild+linux-*/node_modules/@esbuild/linux-*/bin/esbuild',
  'node_modules/.pnpm/@cloudflare+workerd-linux-*/node_modules/@cloudflare/workerd-linux-*/bin/workerd',
  'node_modules/.pnpm/wrangler@*/node_modules/wrangler/wrangler-dist',
  'node_modules/.pnpm/miniflare@*/node_modules/miniflare/dist',
  'node_modules/.pnpm/vite@*/node_modules/vite/dist',
  'node_modules/.pnpm/@rollup+rollup-linux-*/node_modules/@rollup/rollup-linux-*',
] as const

/**
 * Every file under {@link DEV_HOT_PATHS} read to `/dev/null`, at low priority. It always exits 0:
 * a path that is not there (another platform, a kit without it) is skipped.
 */
export const PREREAD_COMMAND = `cd ${SESSION_WORKSPACE} 2>/dev/null || exit 0; for p in ${DEV_HOT_PATHS.join(' ')}; do [ -e "$p" ] && nice -n 10 find "$p" -type f -exec cat {} + > /dev/null 2>&1; done; exit 0`

/**
 * Right after a restore: page the dev server's biggest files in ({@link PREREAD_COMMAND}) as a
 * BACKGROUND process — it overlaps the bootstrap, and the dev start that follows reads them from
 * the page cache. Started, never awaited; a failure to start it is swallowed — it never fails or
 * delays the boot.
 */
export async function prereadHotFiles(sandbox: SandboxPort): Promise<void> {
  await sandbox.startProcess(PREREAD_COMMAND, { cwd: SESSION_WORKSPACE }).catch(() => {})
}

/** How long {@link stopDevServerGracefully} gives the dev server to leave after its SIGTERM. */
export const DEV_GRACEFUL_STOP_SECONDS = 10

/**
 * SIGTERM the dev server ({@link DEV_PID_FILE}) and wait for it to go: the kit's supervisor passes
 * the SIGTERM to `wrangler` and Vite and exits through JS, so the tree's node processes write their
 * compile cache ({@link NODE_COMPILE_CACHE_DIR}) — a destroyed container's SIGKILL would not.
 * Nothing running, nothing to do; it always exits 0.
 */
export const DEV_GRACEFUL_STOP_COMMAND = `pid=$(cat ${DEV_PID_FILE} 2>/dev/null); if [ -n "$pid" ] && kill -0 "$pid" 2>/dev/null; then kill -TERM "$pid" 2>/dev/null; for i in $(seq 1 ${DEV_GRACEFUL_STOP_SECONDS * 5}); do kill -0 "$pid" 2>/dev/null || break; sleep 0.2; done; fi; exit 0`

/**
 * Before a workspace backup (the container is destroyed right after): stop the dev server politely
 * ({@link DEV_GRACEFUL_STOP_COMMAND}), so the backup carries the dev tree's compile cache. Best
 * effort: never throws.
 */
export async function stopDevServerGracefully(sandbox: SandboxPort): Promise<void> {
  await sandbox
    .exec(DEV_GRACEFUL_STOP_COMMAND, { timeoutMs: (DEV_GRACEFUL_STOP_SECONDS + 20) * 1000 })
    .catch(() => {})
}

/**
 * The install and the bootstrap run one at a time per container (`flock`): a step attempt the
 * platform re-runs while an earlier one is still going (a `wrangler dev` reload resumes a killed
 * attempt later — docs/SESSIONS-LOCAL.md) must not run a second `pnpm install` into the same
 * `node_modules` at once, which fails in seconds with nothing useful said.
 */
export const BOOTSTRAP_LOCK = `${SESSION_LAUNCH_DIR}/bootstrap.lock`
export function serialised(command: string, waitMs: number): string {
  return `mkdir -p ${SESSION_LAUNCH_DIR} && flock -w ${Math.ceil(waitMs / 1000)} ${BOOTSTRAP_LOCK} ${command}`
}

/**
 * Upserts `KEY=value` lines into a dotenv file from `LAUNCH_DEV_VARS` (JSON) — Node, not `sed`,
 * because a value may carry `&` or `/`, which a sed replacement would mangle.
 */
export const DEV_VARS_SCRIPT = `import { existsSync, readFileSync, writeFileSync } from 'node:fs'
const file = process.argv[2]
const vars = JSON.parse(process.env.LAUNCH_DEV_VARS || '{}')
let text = existsSync(file) ? readFileSync(file, 'utf8') : ''
for (const [key, value] of Object.entries(vars)) {
  const line = key + '=' + value
  const re = new RegExp('^' + key + '=.*$', 'm')
  if (re.test(text)) text = text.replace(re, () => line)
  else text += (text === '' || text.endsWith('\\n') ? '' : '\\n') + line + '\\n'
}
writeFileSync(file, text)
`

/**
 * `.claude/settings.local.json` in the checkout (plan §1.3): a hard `deny` on pushing and on
 * touching the remote or git config. Launch owns pushes and PRs — `checkpoint.ts` pushes
 * `session/<short>`, `ship.ts` opens the PR through the GitHub App — never the agent. Turns run
 * with `--permission-mode bypassPermissions` (`claude-stream.ts`), where deny rules are still
 * honoured and allow rules have no effect, so there is no allow list. Excluded from git through
 * `.git/info/exclude`, so it never lands in a commit.
 */
export function claudeSettingsLocal(): string {
  return `${JSON.stringify(
    {
      permissions: {
        deny: ['Bash(git push:*)', 'Bash(git remote:*)', 'Bash(git config:*)'],
      },
    },
    null,
    2
  )}\n`
}

export interface SessionBootstrapContext {
  sandbox: SandboxPort
  /** The database the checkout runs on — a SECRET (see the header). */
  dbUri: string
  dev: SessionDevEnv
  /** A resume against an already-prepared database: the parts of the kit bootstrap to leave out. */
  skip?: readonly BootstrapSkip[]
  /**
   * Run `pnpm install` before the kit bootstrap (default). False: `node_modules` is already the
   * lockfile's — a workspace restored from the app's prebuild whose lockfile matched (issue #16).
   */
  install?: boolean
  /**
   * The running step's detail, called only when it changes: `pnpm install`, then the kit
   * bootstrap's latest `✔ n/10 name` ({@link bootstrapProgressOf}). Never carries a secret.
   */
  onProgress?: (detail: string) => void | Promise<void>
  /** How often the long commands are polled (`SESSION_CALL_LIMITS.commandPollMs`). */
  pollMs?: number
  /** Caps each command's own deadline (`BOOTSTRAP_TIMEOUTS`) — the steps pass `execMaxMs`. */
  maxCommandMs?: number
  /** Test hook: the poll's sleep. */
  sleep?: (ms: number) => Promise<void>
  /**
   * Whether the container is no longer the one the boot prepared (the steps read the boot
   * marker): a long command in a replaced container then fails at once, rather than at its
   * deadline (`runInBackground`'s `replaced`).
   */
  replaced?: () => Promise<boolean>
}

export interface BootstrapTimings {
  installMs: number
  bootstrapMs: number
  /** False when the install was left out (`SessionBootstrapContext.install`). */
  installed: boolean
}

/** A failed phase: the exit code and the TAIL of its output (never an env dump). */
export class SessionBootstrapError extends Error {
  constructor(
    readonly phase: 'install' | 'bootstrap' | 'dev-vars' | 'dev',
    message: string
  ) {
    super(message)
    this.name = 'SessionBootstrapError'
  }
}

/** How many lines of a failed command's output travel in its error (the page and the log). */
export const ERROR_TAIL_LINES = 40

/**
 * `text` with `secrets` (the database URI) replaced wherever they appear, anything shaped like a
 * connection string with a password replaced, and ANSI colour codes stripped. Pure.
 */
export function redactLog(text: string, secrets: readonly string[] = []): string {
  let clean = text
  for (const secret of secrets) if (secret) clean = clean.split(secret).join('<database url>')
  return (
    clean
      .replace(/[a-z][a-z0-9+.-]*:\/\/[^\s'"@/]*:[^\s'"@/]*@[^\s'"]*/gi, '<connection string>')
      // biome-ignore lint/suspicious/noControlCharactersInRegex: ANSI colour codes from the kit's output
      .replace(/\u001b\[[0-9;]*m/g, '')
  )
}

/**
 * What a failed command said, for the person: its own error lines first (the kit's bootstrap
 * prints `bootstrap: …` for a usage error and `✖ n/10 …` for a failed step, before any usage text
 * or child output), then the last {@link ERROR_TAIL_LINES} lines — stdout AND stderr, because the
 * kit's bootstrap prints a failed child's output (pnpm's own error) under its `✖` line. `secrets`
 * (the database URI) are replaced wherever they appear, and so is anything shaped like a
 * connection string with a password.
 */
export function tailOf(text: string, secrets: readonly string[] = [], lines = ERROR_TAIL_LINES) {
  const all = redactLog(text, secrets)
    .split('\n')
    .filter(line => line.trim() !== '')
  const headline = all.filter(line => /^(bootstrap:|\S*✖|error\b|Error\b|ERR_)/.test(line.trim()))
  const tail = all.slice(-lines).filter(line => !headline.includes(line))
  return [...headline.slice(0, 4), ...tail].join('\n')
}

/**
 * The detail a running boot step shows for the kit bootstrap's progress: its latest `✔ n/10 name`
 * (or `✖ n/10 name`) line, as `✔ 4/10 database` — the mark, the count and the step's own name,
 * nothing else of the line (its `verify` text could name the database host). Null when the log has
 * no such line yet.
 */
export function bootstrapProgressOf(log: string): string | null {
  // biome-ignore lint/suspicious/noControlCharactersInRegex: ANSI colour codes from the kit's output
  const clean = log.replace(/\u001b\[[0-9;]*m/g, '')
  let found: string | null = null
  for (const m of clean.matchAll(/^\s*([✔✖])\s+(\d+\/\d+)\s+([a-z][a-z-]*)/gm)) {
    found = `${m[1]} ${m[2]} ${m[3]}`
  }
  return found
}

/** What a running boot step shows while the install runs (pnpm is silent: `--reporter=silent`). */
export const INSTALL_PROGRESS = 'pnpm install'
/** ...and when the kit bootstrap starts, before its first `✔ n/10` line. */
export const BOOTSTRAP_PROGRESS = "starting the app's bootstrap"

/**
 * One long phase as a polled background command (`background-command.ts`), under the bootstrap
 * lock (`serialised`): a non-zero exit and a deadline both become a {@link SessionBootstrapError}
 * with the redacted tail of what it printed.
 */
async function runPhase(
  ctx: SessionBootstrapContext,
  phase: 'install' | 'bootstrap',
  opts: {
    command: string
    timeoutMs: number
    env: Record<string, string>
    what: string
    progressOf?: (log: string) => string | null
  }
): Promise<void> {
  const timeoutMs = Math.min(opts.timeoutMs, ctx.maxCommandMs ?? opts.timeoutMs)
  const report = ctx.onProgress
  let result: { exitCode: number; stdout: string }
  try {
    result = await runInBackground(ctx.sandbox, {
      name: phase,
      dir: SESSION_LAUNCH_DIR,
      command: serialised(opts.command, timeoutMs),
      cwd: SESSION_WORKSPACE,
      env: opts.env,
      timeoutMs,
      ...(ctx.pollMs !== undefined ? { pollMs: ctx.pollMs } : {}),
      ...(ctx.sleep ? { sleep: ctx.sleep } : {}),
      ...(ctx.replaced ? { replaced: ctx.replaced } : {}),
      ...(report && opts.progressOf ? { onProgress: report, progressOf: opts.progressOf } : {}),
    })
  } catch (err) {
    if (!(err instanceof BackgroundCommandTimeoutError)) throw err
    const tail = tailOf(err.log, [ctx.dbUri])
    throw new SessionBootstrapError(
      phase,
      `${opts.what} did not finish within ${formatDuration(err.timeoutMs)}; Launch stopped it${tail ? `:\n${tail}` : ''}`
    )
  }
  if (result.exitCode !== 0) {
    throw new SessionBootstrapError(
      phase,
      `${opts.what} failed (exit ${result.exitCode}):\n${tailOf(result.stdout, [ctx.dbUri])}`
    )
  }
}

/** The preload's {@link BOOTSTRAP_KEEP_ENV}: the tracked files the bootstrap never writes. */
export function bootstrapKeepEnv(): Record<string, string> {
  return {
    [BOOTSTRAP_KEEP_ENV]: SESSION_DEV_TRACKED_FILES.map(f => `${SESSION_WORKSPACE}/${f}`).join(','),
  }
}

/** The kit bootstrap against `ctx.dbUri`, then the dev-server keys. See the header. */
export async function sessionBootstrap(ctx: SessionBootstrapContext): Promise<BootstrapTimings> {
  const { sandbox, dev } = ctx
  const env = sessionProcessEnv(dev)
  let shown: string | null = null
  const show = async (detail: string) => {
    if (!ctx.onProgress || detail === shown) return
    shown = detail
    await Promise.resolve(ctx.onProgress(detail)).catch(() => {})
  }
  const progressCtx: SessionBootstrapContext = { ...ctx, onProgress: show }

  // The container reaches its database directly — so exactly that endpoint joins the allow-list,
  // REPLACING any earlier one (the `dev` a prepare run used is dropped when the session's own
  // branch takes over). A URI that is not a Neon endpoint throws here, before anything runs.
  await sandbox.setAllowedHosts(sessionAllowedHosts(sessionDbEgressHosts(ctx.dbUri)))

  const t0 = Date.now()
  const installed = ctx.install !== false
  if (installed) {
    await show(INSTALL_PROGRESS)
    await installDependencies(progressCtx)
  }

  const t1 = Date.now()
  await sandbox.writeFile(NOT_ROOT_PRELOAD, NOT_ROOT_PRELOAD_SCRIPT)
  // The database check, the kit's second install and its wrangler login check never run in a
  // sandbox: through the kit's own flags when its bootstrap takes them, else the preload's.
  const invocation = bootstrapInvocation(await checkoutTakesKitFlags(sandbox), ctx.skip)
  await show(BOOTSTRAP_PROGRESS)
  // The bootstrap prints its own `✖ n/10` line and the failing child's output under it.
  await runPhase(progressCtx, 'bootstrap', {
    command: invocation.command,
    timeoutMs: BOOTSTRAP_TIMEOUTS.bootstrapMs,
    env: { ...env, ...invocation.env, ...bootstrapKeepEnv(), LAUNCH_DB_URL: ctx.dbUri },
    what: "The app's bootstrap",
    progressOf: bootstrapProgressOf,
  })
  const t2 = Date.now()

  await writeDevVars(sandbox, `${SESSION_WORKSPACE}/apps/web/.dev.vars`, sessionDevVars(dev))
  return { installMs: t1 - t0, bootstrapMs: t2 - t1, installed }
}

/**
 * Step 1 of {@link sessionBootstrap} on its own: `pnpm install` in the checkout, as a polled
 * background command under the bootstrap lock. What a `prebuild` run installs with (issue #16) —
 * the same command, so the prebuild's `node_modules` is exactly what a session's install makes.
 */
export async function installDependencies(
  ctx: Omit<SessionBootstrapContext, 'dbUri'> & { dbUri?: string }
): Promise<void> {
  await runPhase({ ...ctx, dbUri: ctx.dbUri ?? '' }, 'install', {
    command: INSTALL_COMMAND,
    timeoutMs: BOOTSTRAP_TIMEOUTS.installMs,
    env: sessionProcessEnv(ctx.dev),
    what: 'pnpm install',
  })
}

/** The dependency lockfile a prebuild is keyed on (issue #16): pnpm's, at the checkout's root. */
export const LOCKFILE = 'pnpm-lock.yaml'

/**
 * What a checkout IS, for the prebuild (issue #16): its commit, that commit's tree, and the sha256
 * of {@link LOCKFILE} (`lockfile=` empty when there is none) — `head=<sha>`, `tree=<sha>`,
 * `lockfile=<hex>` lines.
 */
export const WORKSPACE_FACTS_COMMAND = `cd ${SESSION_WORKSPACE} && echo "head=$(git rev-parse HEAD)" && echo "tree=$(git rev-parse 'HEAD^{tree}')" && echo "lockfile=$( [ -f ${LOCKFILE} ] && sha256sum ${LOCKFILE} | cut -c1-64 )"`

export interface WorkspaceFacts {
  headSha: string
  treeSha: string
  /** Null when the checkout has no lockfile (nothing to compare: every restore installs). */
  lockfileHash: string | null
}

/** {@link WORKSPACE_FACTS_COMMAND} in `sandbox`; throws when git cannot answer. */
export async function workspaceFacts(sandbox: SandboxPort): Promise<WorkspaceFacts> {
  const result = await sandbox.exec(WORKSPACE_FACTS_COMMAND, { timeoutMs: 60_000 })
  const headSha = /head=([0-9a-f]{40,64})/.exec(result.stdout)?.[1]
  const treeSha = /tree=([0-9a-f]{40,64})/.exec(result.stdout)?.[1]
  if (result.exitCode !== 0 || !headSha || !treeSha) {
    throw new Error(`git could not read the workspace: ${tailOf(result.stderr, [], 5)}`)
  }
  return {
    headSha,
    treeSha,
    lockfileHash: /lockfile=([0-9a-f]{64})/.exec(result.stdout)?.[1] ?? null,
  }
}

/** Upsert `vars` into the dotenv file at `path` (inside the container). */
export async function writeDevVars(
  sandbox: SandboxPort,
  path: string,
  vars: Record<string, string>
): Promise<void> {
  const script = `${SESSION_LAUNCH_DIR}/dev-vars.mjs`
  await sandbox.writeFile(script, DEV_VARS_SCRIPT)
  const result = await sandbox.exec(`node ${script} ${path}`, {
    env: { LAUNCH_DEV_VARS: JSON.stringify(vars) },
  })
  if (result.exitCode !== 0) {
    throw new SessionBootstrapError('dev-vars', `Could not write ${path}: ${tailOf(result.stderr)}`)
  }
}

/** One port wait inside {@link startDevServer}: short, so an end request is seen between them. */
export const DEV_WAIT_CHUNK_MS = 20_000

export interface StartDevServerOptions {
  /** Called between wait chunks; throw from it to stop waiting (the person ended the session). */
  checkpoint?: () => Promise<void>
  /** Test hook: the wait chunk length. */
  chunkMs?: number
}

/**
 * The dev stack's readiness, as ONE wait (`waitForPort` with `followedBy`): `:8787/api/health` 2xx
 * FIRST, then a bare TCP connect to Vite's `:5173`. Never a GET of the UI's `/` while the API is
 * still booting: Vite would transform the whole UI graph on the same two vCPUs `wrangler dev` is
 * starting on (measured -30 % wall and -1.4 s CPU locally without it).
 */
export const DEV_READY_PROBE = {
  port: SESSION_API_PORT,
  path: '/api/health',
  followedBy: [{ port: SESSION_UI_PORT, tcp: true }],
} as const

/** How long the dev stack gets to answer {@link DEV_READY_PROBE}, all chunks together. */
export const DEV_READY_TIMEOUT_MS = BOOTSTRAP_TIMEOUTS.apiMs + BOOTSTRAP_TIMEOUTS.uiMs

/**
 * The dev server in the background ({@link DEV_START_COMMAND}), then the stack answering
 * ({@link DEV_READY_PROBE}, one in-container wait per chunk). Returns the process id. The wait is
 * chunked ({@link DEV_WAIT_CHUNK_MS}) with `opts.checkpoint` between chunks, and each chunk fails at
 * once when the dev server's process is gone (`DEV_PID_FILE`) — with the tail of its output
 * (`DEV_LOG_FILE`) as the reason, rather than a curl loop against nothing for minutes. Once it is
 * ready, the UI's `/` is warmed in the background ({@link DEV_WARM_COMMAND}, never waited on).
 */
export async function startDevServer(
  sandbox: SandboxPort,
  dev: SessionDevEnv,
  opts: StartDevServerOptions = {}
): Promise<{ processId: string }> {
  // The dev server runs on the session's own, git-ignored config — never on an edited tracked
  // toml. The script that writes it runs inside the dev start (`DEV_COMMAND`'s preload).
  await writeSessionWranglerScript(sandbox)
  const proc = await sandbox.startProcess(DEV_START_COMMAND, {
    cwd: SESSION_WORKSPACE,
    env: sessionProcessEnv(dev),
  })
  const chunkMs = opts.chunkMs ?? DEV_WAIT_CHUNK_MS
  const { port, path, followedBy } = DEV_READY_PROBE
  const deadline = Date.now() + DEV_READY_TIMEOUT_MS
  try {
    for (;;) {
      await opts.checkpoint?.()
      const left = deadline - Date.now()
      try {
        await sandbox.waitForPort(port, {
          path,
          followedBy,
          timeoutMs: Math.max(1000, Math.min(chunkMs, left)),
          pidFile: DEV_PID_FILE,
        })
        break
      } catch (err) {
        // Only "not yet" is retried; a dead process or a broken sandbox fails the step now.
        if (!isChunkTimeout(err)) throw err
        if (Date.now() >= deadline) {
          throw new Error(
            `port ${port}${path} (then ${followedBy.map(t => t.port).join(', ')}) did not answer within ${DEV_READY_TIMEOUT_MS / 1000} s`
          )
        }
      }
    }
  } catch (err) {
    if (!(err instanceof SandboxProcessExitedError) && !isPortTimeout(err)) throw err
    const log = await sandbox.readFile(DEV_LOG_FILE).catch(() => null)
    const reason =
      err instanceof SandboxProcessExitedError
        ? 'the dev server exited before its ports answered'
        : err instanceof Error
          ? err.message
          : String(err)
    throw new SessionBootstrapError(
      'dev',
      `The app's dev server did not come up: ${reason}${log ? `\n${tailOf(log)}` : ''}`
    )
  }
  // The preview's first paint: Vite's transform starts now, not when the browser first asks.
  await sandbox.startProcess(DEV_WARM_COMMAND, { cwd: SESSION_WORKSPACE }).catch(() => {})
  return { processId: proc.id }
}

/** The kit's own "stop this checkout's dev tree" (its supervisor owns the ports). */
export const DEV_STOP_COMMAND = 'pnpm dev:stop'

/** How long a warm resume gives the dev stack to answer before it restarts the dev server. */
export const DEV_PROBE_MS = 3_000

/** The dev stack answers now ({@link DEV_READY_PROBE}: the API's health, then Vite) — one call. */
export async function devServerAnswers(sandbox: SandboxPort): Promise<boolean> {
  try {
    await sandbox.waitForPort(DEV_READY_PROBE.port, {
      path: DEV_READY_PROBE.path,
      followedBy: DEV_READY_PROBE.followedBy,
      timeoutMs: DEV_PROBE_MS,
    })
    return true
  } catch {
    return false
  }
}

/**
 * The dev step of a WARM resume (`warm.ts`): the kept container's dev server is reused when both
 * ports still answer; otherwise whatever is left of it is stopped (`pnpm dev:stop` — a half-dead
 * tree would hold the strict ports) and it is started again.
 */
export async function resumeDevServer(
  sandbox: SandboxPort,
  dev: SessionDevEnv,
  opts: StartDevServerOptions = {}
): Promise<{ reused: boolean }> {
  if (await devServerAnswers(sandbox)) return { reused: true }
  await sandbox.exec(DEV_STOP_COMMAND, {
    cwd: SESSION_WORKSPACE,
    env: sessionProcessEnv(dev),
    timeoutMs: 60_000,
  })
  await startDevServer(sandbox, dev, opts)
  return { reused: false }
}

const isPortTimeout = (err: unknown) =>
  err instanceof Error && /^port \d+.* did not answer within/.test(err.message)

/** One wait chunk ran out (the adapter's `Port N did not answer within`, the fake's `never opened`). */
const isChunkTimeout = (err: unknown) =>
  !(err instanceof SandboxProcessExitedError) &&
  err instanceof Error &&
  err.name !== 'SessionStepTimeoutError' &&
  /did not answer within|never opened/.test(err.message)
