/**
 * A coding session's dev setup never changes a tracked file (the hola-world PR #2 bug: the kit's
 * `bootstrap --offline` commented `[ai]` out of both wrangler tomls in place, the typecheck
 * regenerated `worker-configuration.d.ts` without `AI`, and the checkpoint committed all three).
 * The scripts run for REAL here — Node, bash and git in scratch repositories — the way the
 * container runs them:
 *
 * - the bootstrap preload drops the kit bootstrap's writes to the tracked files;
 * - the session's own wrangler config is the tracked toml with `[ai]` off (the kit's own toggle,
 *   byte for byte), git-ignored, and wrangler's redirect points `wrangler dev` at it;
 * - a resume puts back what an earlier Launch committed (against the session's base);
 * - the checkpoint's guard refuses the toggle in staged content.
 *
 * Plus the `FakeSandbox` side: the bootstrap is told which files to keep, and the dev server
 * starts only after its config is written.
 */
import { execFileSync, spawnSync } from 'node:child_process'
import { mkdirSync, mkdtempSync, readFileSync, realpathSync, rmSync, writeFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import path from 'node:path'
import { afterEach, describe, expect, it } from 'vitest'
import {
  DEV_SETUP_GUARD_SCRIPT,
  parseDevSetupDrift,
  parseWorkflowChanges,
  parseWorkflowHistory,
  workflowsGuardScript,
} from '@/api/services/sessions/checkpoint'
import {
  BOOTSTRAP_KEEP_ENV,
  DEV_SETUP_HEAL_SCRIPT,
  healDevSetup,
  NOT_ROOT_PRELOAD_SCRIPT,
  SESSION_DEV_EXCLUDES,
  SESSION_DEV_TRACKED_FILES,
  SESSION_WRANGLER_CONFIG,
  SESSION_WRANGLER_SCRIPT,
  sessionBootstrap,
  startDevServer,
  WRANGLER_REDIRECT,
} from '@/api/services/sessions/rocketflare-dev'
import { checkoutScript } from '@/api/services/sessions/steps'
import { toggleAiBlock } from '../../../../scripts/lib/bootstrap-lib.mjs'
import { FakeSandbox } from '../helpers/fake-sandbox'

const WEB_DIR = path.resolve(__dirname, '../..')
/** A real kit toml (this app's own): the `[ai]` block with its comment lines and `remote = true`. */
const TOML = readFileSync(path.join(WEB_DIR, 'wrangler.toml'), 'utf8')
const STAGING = readFileSync(path.join(WEB_DIR, 'wrangler.staging.toml'), 'utf8')
const TYPES = [
  '/* eslint-disable */',
  '// Generated by Wrangler by running `wrangler types` (hash: 03bca1328ab1cfcd96f7a7d3e2011cf6)',
  'interface __BaseEnv_Env {',
  '\tFILES: R2Bucket;',
  '\tAI: Ai;',
  '\tASSETS: Fetcher;',
  '}',
  '',
].join('\n')
/** What `wrangler types` wrote from a toggled toml: no `AI`, another hash. */
const TYPES_OFF = TYPES.replace('\tAI: Ai;\n', '').replace('03bca1328ab1', 'ffffffffffff')

const dirs: string[] = []
afterEach(() => {
  for (const dir of dirs.splice(0)) rmSync(dir, { recursive: true, force: true })
})

function scratch(prefix: string): string {
  const dir = realpathSync(mkdtempSync(path.join(tmpdir(), prefix)))
  dirs.push(dir)
  return dir
}

/** A scratch checkout shaped like a kit app, committed once (the session's base). */
function repo(files: Record<string, string> = {}) {
  const dir = scratch('launch-devsetup-')
  const git = (...args: string[]) =>
    execFileSync('git', ['-c', 'user.email=t@t', '-c', 'user.name=t', ...args], {
      cwd: dir,
      encoding: 'utf8',
    }).trim()
  const put = (rel: string, text: string) => {
    mkdirSync(path.dirname(path.join(dir, rel)), { recursive: true })
    writeFileSync(path.join(dir, rel), text)
  }
  const read = (rel: string) => readFileSync(path.join(dir, rel), 'utf8')
  git('init', '-q')
  put('apps/web/wrangler.toml', TOML)
  put('apps/web/wrangler.staging.toml', STAGING)
  put('apps/web/worker-configuration.d.ts', TYPES)
  put('.gitignore', 'node_modules/\n')
  for (const [rel, text] of Object.entries(files)) put(rel, text)
  git('add', '-A')
  git('commit', '-qm', 'base')
  const commit = (message: string) => {
    git('add', '-A')
    git('commit', '-qm', message)
    return git('rev-parse', 'HEAD')
  }
  return { dir, git, put, read, base: git('rev-parse', 'HEAD'), commit }
}

/** A child's environment: PATH and what the test adds, nothing of the test process's own. */
const childEnv = (extra: Record<string, string> = {}) =>
  ({ PATH: process.env.PATH ?? '', ...extra }) as unknown as NodeJS.ProcessEnv

const node = (cwd: string, script: string, args: string[] = []) => {
  const file = path.join(cwd, `.launch-${Math.random().toString(36).slice(2)}.mjs`)
  writeFileSync(file, script)
  try {
    const res = spawnSync(process.execPath, [file, ...args], {
      cwd,
      encoding: 'utf8',
      env: childEnv(),
    })
    expect(res.status, res.stderr).toBe(0)
    return res.stdout
  } finally {
    rmSync(file)
  }
}

const bash = (cwd: string, script: string) =>
  execFileSync('bash', ['-c', script], { cwd, encoding: 'utf8' })

describe('the bootstrap preload keeps the tracked files', () => {
  it('drops the kit bootstrap’s writes to the kept paths (a NAMED writeFileSync import), and only those', () => {
    const { dir, read } = repo()
    const preload = path.join(dir, '.preload.mjs')
    writeFileSync(preload, NOT_ROOT_PRELOAD_SCRIPT)
    // A stand-in for the kit's `setAiBlocks('off')` and its `.dev.vars` write.
    const bootstrap = path.join(dir, '.bootstrap.mjs')
    writeFileSync(
      bootstrap,
      `import { readFileSync, writeFileSync } from 'node:fs'
for (const f of ['apps/web/wrangler.toml', 'apps/web/wrangler.staging.toml']) {
  writeFileSync(f, readFileSync(f, 'utf8').replace(/^\\[ai\\]$/m, '# [ai]'))
}
writeFileSync('apps/web/worker-configuration.d.ts', 'regenerated')
writeFileSync('apps/web/.dev.vars', 'DATABASE_URL=x\\n')
`
    )
    const keep = SESSION_DEV_TRACKED_FILES.map(f => path.join(dir, f)).join(',')
    const res = spawnSync(process.execPath, ['--import', preload, bootstrap], {
      cwd: dir,
      encoding: 'utf8',
      env: childEnv({ [BOOTSTRAP_KEEP_ENV]: keep }),
    })
    expect(res.status, res.stderr).toBe(0)
    expect(read('apps/web/wrangler.toml')).toBe(TOML)
    expect(read('apps/web/wrangler.staging.toml')).toBe(STAGING)
    expect(read('apps/web/worker-configuration.d.ts')).toBe(TYPES)
    expect(read('apps/web/.dev.vars')).toBe('DATABASE_URL=x\n')
  })

  it('without the variable, writes go through (the preload changes nothing else)', () => {
    const { dir, read } = repo()
    const preload = path.join(dir, '.preload.mjs')
    writeFileSync(preload, NOT_ROOT_PRELOAD_SCRIPT)
    const bootstrap = path.join(dir, '.bootstrap.mjs')
    writeFileSync(
      bootstrap,
      "import { writeFileSync } from 'node:fs'\nwriteFileSync('apps/web/wrangler.toml', 'x')\n"
    )
    const res = spawnSync(process.execPath, ['--import', preload, bootstrap], {
      cwd: dir,
      encoding: 'utf8',
      env: childEnv(),
    })
    expect(res.status, res.stderr).toBe(0)
    expect(read('apps/web/wrangler.toml')).toBe('x')
  })
})

describe('the session’s own wrangler config', () => {
  it('is the tracked toml with [ai] off — the kit’s own toggle — beside it, git-ignored, with the redirect', () => {
    const { dir, read, git } = repo()
    const out = node(dir, SESSION_WRANGLER_SCRIPT)
    expect(out.trim()).toBe('session-config ai=on')

    // The tracked files are exactly as committed; git sees nothing new.
    expect(read('apps/web/wrangler.toml')).toBe(TOML)
    expect(git('status', '--porcelain', '--untracked-files=all')).toBe('')

    const session = read(SESSION_WRANGLER_CONFIG)
    const body = session.split('\n').filter(line => !line.startsWith('# Generated by Launch'))
    expect(session.startsWith('# Generated by Launch')).toBe(true)
    // Byte for byte what `pnpm bootstrap --offline` would have written into the tracked toml.
    expect(session.slice(session.indexOf('\n', session.indexOf('Never commit it')) + 1)).toBe(
      toggleAiBlock(TOML, 'off')
    )
    expect(body.some(line => /^\[ai\]/.test(line))).toBe(false)
    expect(session).toMatch(/^# \[ai\]$/m)

    // wrangler reads `configPath` relative to the redirect file's own directory.
    const redirect = JSON.parse(read(WRANGLER_REDIRECT))
    expect(path.resolve(path.dirname(path.join(dir, WRANGLER_REDIRECT)), redirect.configPath)).toBe(
      path.join(dir, SESSION_WRANGLER_CONFIG)
    )
    expect(read('.git/info/exclude')).toContain(`/${SESSION_WRANGLER_CONFIG}\n`)
  })

  it('follows the agent’s own toml edits on the next run, and never repeats an exclude line', () => {
    const { dir, read, put } = repo()
    node(dir, SESSION_WRANGLER_SCRIPT)
    put('apps/web/wrangler.toml', `${TOML}\n[[kv_namespaces]]\nbinding = "NEW_KV"\nid = "x"\n`)
    node(dir, SESSION_WRANGLER_SCRIPT)
    expect(read(SESSION_WRANGLER_CONFIG)).toContain('binding = "NEW_KV"')
    const exclude = read('.git/info/exclude').split('\n')
    for (const line of SESSION_DEV_EXCLUDES) {
      expect(exclude.filter(l => l === line)).toHaveLength(1)
    }
  })

  it('an app whose toml has no [ai] (or has it off already) gets a plain copy', () => {
    const { dir, read, put } = repo()
    put('apps/web/wrangler.toml', 'name = "x"\nmain = "src/worker.ts"\n')
    expect(node(dir, SESSION_WRANGLER_SCRIPT).trim()).toBe('session-config ai=absent')
    expect(read(SESSION_WRANGLER_CONFIG)).toContain('name = "x"\nmain = "src/worker.ts"\n')
  })

  it('the checkout writes the same exclude lines', () => {
    const script = checkoutScript({
      url: 'https://github.com/o/r.git',
      baseRef: 'main',
      branch: null,
    })
    for (const line of SESSION_DEV_EXCLUDES) expect(script).toContain(`'${line}'`)
  })
})

describe('healing a branch an earlier Launch checkpointed', () => {
  /** The branch as the bug left it: both tomls toggled, the types without `AI`. */
  function toggledBranch(extra: (r: ReturnType<typeof repo>) => void = () => {}) {
    const r = repo()
    r.git('checkout', '-qb', 'session/abc')
    r.put('apps/web/wrangler.toml', toggleAiBlock(TOML, 'off'))
    r.put('apps/web/wrangler.staging.toml', toggleAiBlock(STAGING, 'off'))
    r.put('apps/web/worker-configuration.d.ts', TYPES_OFF)
    r.put('apps/web/src/ui/Login.tsx', 'the agent’s change\n')
    extra(r)
    r.commit('Launch session abc: turn 1')
    return r
  }

  it('puts the three files back as they are at the base; the agent’s change stays', () => {
    const r = toggledBranch()
    const out = node(r.dir, DEV_SETUP_HEAL_SCRIPT, [r.base])
    expect(out.trim().split('\n').sort()).toEqual(
      SESSION_DEV_TRACKED_FILES.map(f => `healed\t${f}`).sort()
    )
    expect(r.read('apps/web/wrangler.toml')).toBe(TOML)
    expect(r.read('apps/web/wrangler.staging.toml')).toBe(STAGING)
    expect(r.read('apps/web/worker-configuration.d.ts')).toBe(TYPES)
    // The branch's diff from the base is the agent's work alone once the heal is committed.
    r.commit('heal')
    expect(r.git('diff', '--name-only', r.base, 'HEAD')).toBe('apps/web/src/ui/Login.tsx')
  })

  it('keeps the agent’s own toml edits while turning [ai] back on; types it changed otherwise are left for the gate', () => {
    const r = toggledBranch(b => {
      b.put(
        'apps/web/wrangler.toml',
        `${toggleAiBlock(TOML, 'off')}\n[[kv_namespaces]]\nbinding = "NEW_KV"\nid = "x"\n`
      )
      b.put(
        'apps/web/worker-configuration.d.ts',
        TYPES_OFF.replace('FILES', 'FILES: R2Bucket;\n\tNEW_KV')
      )
    })
    const out = node(r.dir, DEV_SETUP_HEAL_SCRIPT, [r.base])
    expect(out).toContain('healed\tapps/web/wrangler.toml')
    expect(out).not.toContain('worker-configuration')
    const toml = r.read('apps/web/wrangler.toml')
    expect(toml).toMatch(/^\[ai\]$/m)
    expect(toml).toContain('binding = "NEW_KV"')
    expect(toml).toBe(`${TOML}\n[[kv_namespaces]]\nbinding = "NEW_KV"\nid = "x"\n`)
  })

  it('an untouched branch, and a base whose [ai] is off on purpose, are left alone', () => {
    const clean = repo()
    expect(node(clean.dir, DEV_SETUP_HEAL_SCRIPT, [clean.base])).toBe('')

    const offline = repo({ 'apps/web/wrangler.toml': toggleAiBlock(TOML, 'off') })
    expect(node(offline.dir, DEV_SETUP_HEAL_SCRIPT, [offline.base])).toBe('')
    expect(offline.read('apps/web/wrangler.toml')).toBe(toggleAiBlock(TOML, 'off'))
  })

  it('healDevSetup runs it in the checkout with the base and answers the healed paths', async () => {
    const fake = new FakeSandbox().onExec(/heal-dev-setup\.mjs/, {
      stdout: 'healed\tapps/web/wrangler.toml\n',
    })
    expect(await healDevSetup(fake, 'a'.repeat(40))).toEqual(['apps/web/wrangler.toml'])
    expect(fake.execs[0]?.command).toBe(
      `node /workspace/.launch/heal-dev-setup.mjs ${'a'.repeat(40)}`
    )
    expect(fake.execs[0]?.opts?.cwd).toBe('/workspace/app')
    // No base (or not a sha): nothing runs. A failing script heals nothing and fails nothing.
    const none = new FakeSandbox()
    expect(await healDevSetup(none, null)).toEqual([])
    expect(await healDevSetup(none, 'main; rm -rf /')).toEqual([])
    expect(none.execs).toHaveLength(0)
    const broken = new FakeSandbox().onExec(/heal-dev-setup/, { exitCode: 1 })
    expect(await healDevSetup(broken, 'b'.repeat(40))).toEqual([])
  })
})

describe('the checkpoint’s dev-setup guard', () => {
  const guard = (dir: string) => parseDevSetupDrift(bash(dir, DEV_SETUP_GUARD_SCRIPT))

  it('names each staged file carrying the offline toggle', () => {
    const r = repo()
    r.put('apps/web/wrangler.toml', toggleAiBlock(TOML, 'off'))
    r.put('apps/web/wrangler.staging.toml', toggleAiBlock(STAGING, 'off'))
    r.git('add', '-A')
    expect(guard(r.dir)).toEqual(['apps/web/wrangler.toml', 'apps/web/wrangler.staging.toml'])
  })

  it('names the types when they lose AI while the staged toml still declares [ai]', () => {
    const r = repo()
    r.put('apps/web/worker-configuration.d.ts', TYPES_OFF)
    r.git('add', '-A')
    expect(guard(r.dir)).toEqual(['apps/web/worker-configuration.d.ts'])
  })

  it('stays quiet for ordinary work, a toggle only in the working tree, an old branch, and the heal', () => {
    const r = repo()
    r.put('apps/web/wrangler.toml', `${TOML}\n# a comment the agent added\n`)
    r.put('apps/web/src/a.ts', 'export {}\n')
    r.git('add', '-A')
    expect(guard(r.dir)).toEqual([])

    // Unstaged: not what the commit would carry.
    r.commit('work')
    r.put('apps/web/wrangler.staging.toml', toggleAiBlock(STAGING, 'off'))
    expect(guard(r.dir)).toEqual([])

    // A branch whose HEAD already carries it (before the heal): nothing NEW is staged.
    r.git('add', '-A')
    r.commit('old launch')
    r.put('apps/web/src/b.ts', 'export {}\n')
    r.git('add', '-A')
    expect(guard(r.dir)).toEqual([])

    // The heal itself (off → on) is what a checkpoint should commit.
    r.put('apps/web/wrangler.staging.toml', STAGING)
    r.git('add', '-A')
    expect(guard(r.dir)).toEqual([])
  })
})

describe('the session steps, against a FakeSandbox', () => {
  const dev = { previewOrigin: null, previewHostSuffix: null }
  const DB_URI = 'postgresql://session_owner:pw@ep-x-000001.us-east-2.aws.neon.tech/neondb'

  it('the kit bootstrap is told to keep the tracked files, and nothing Launch writes is one', async () => {
    const fake = new FakeSandbox()
    await sessionBootstrap({ sandbox: fake, dbUri: DB_URI, dev, pollMs: 1, sleep: async () => {} })
    const run = fake.backgroundRuns.find(r => r.command.includes('scripts/bootstrap.mjs'))
    expect(run?.command).toContain('--offline')
    expect(run?.opts?.env?.[BOOTSTRAP_KEEP_ENV]?.split(',')).toEqual([
      '/workspace/app/apps/web/wrangler.toml',
      '/workspace/app/apps/web/wrangler.staging.toml',
      '/workspace/app/apps/web/worker-configuration.d.ts',
    ])
    for (const file of fake.files.keys()) {
      expect(file).not.toMatch(/wrangler(\.staging)?\.toml$|worker-configuration\.d\.ts$/)
    }
    // No command of Launch's writes one either (the kit's `pnpm typecheck` is the gate's, later).
    for (const command of fake.commands) expect(command).not.toMatch(/wrangler types|pnpm types/)
  })

  it('the dev server starts on the session config: written first, a failure stops the start', async () => {
    const fake = new FakeSandbox().onProcess(/exec pnpm dev/, {
      lines: ['ready'],
      ports: [5173, 8787],
      hang: true,
    })
    await startDevServer(fake, dev, { chunkMs: 10 })
    expect(fake.files.get('/workspace/.launch/session-wrangler.mjs')).toBe(SESSION_WRANGLER_SCRIPT)
    const order = fake.commands.filter(c => /session-wrangler|exec pnpm dev/.test(c))
    expect(order[0]).toBe('node /workspace/.launch/session-wrangler.mjs')
    expect(order[1]).toContain('exec pnpm dev')

    const broken = new FakeSandbox().onExec(/session-wrangler/, {
      exitCode: 1,
      stderr: 'no apps/web/wrangler.toml in the checkout',
    })
    const err = await startDevServer(broken, dev).catch(e => e)
    expect(err.message).toContain('no apps/web/wrangler.toml')
    expect(broken.commands.some(c => c.includes('pnpm dev'))).toBe(false)
  })
})

describe('the checkpoint’s workflows guard (an ordinary session)', () => {
  const CI = '.github/workflows/ci.yml'
  const guard = (dir: string, since: string | null) =>
    parseWorkflowChanges(bash(dir, workflowsGuardScript(since)))

  it('names a staged workflow change, and stays quiet for ordinary work', () => {
    const r = repo({ [CI]: 'name: CI\n' })
    r.put('apps/web/src/a.ts', 'export {}\n')
    r.git('add', '-A')
    expect(guard(r.dir, r.base)).toEqual([])
    r.put(CI, 'name: CI\non: push\n')
    r.put('.github/workflows/deploy.yml', 'name: Deploy\n')
    r.git('add', '-A')
    expect(guard(r.dir, r.base)).toEqual([
      '.github/workflows/ci.yml',
      '.github/workflows/deploy.yml',
    ])
    // Unstaged only: not what this save would carry.
    r.git('reset', '-q')
    expect(guard(r.dir, r.base)).toEqual([])
  })

  it('names a workflow change in a commit not yet pushed', () => {
    const r = repo({ [CI]: 'name: CI\n' })
    r.put(CI, 'name: CI changed\n')
    const edited = r.commit('edit ci')
    expect(guard(r.dir, r.base)).toEqual([CI])
    // Already pushed (the row's head): nothing new.
    expect(guard(r.dir, edited)).toEqual([])
  })

  it('a workflow edit a later commit undid is not refused — it is history, and a soft reset drops it', () => {
    const r = repo({ [CI]: 'name: CI\n' })
    r.put(CI, 'name: CI changed\n')
    r.commit('edit ci')
    r.put(CI, 'name: CI\n')
    r.put('apps/web/src/a.ts', 'export {}\n')
    r.commit('revert ci')
    r.git('add', '-A')
    const out = bash(r.dir, workflowsGuardScript(r.base))
    expect(parseWorkflowChanges(out)).toEqual([])
    // GitHub checks each pushed commit, so the round trip would still be refused on push.
    expect(parseWorkflowHistory(out)).toEqual([CI])
    // What the checkpoint does next: fold the unpushed commits into its own (the tree stays).
    r.git('reset', '-q', '--soft', r.base)
    expect(parseWorkflowHistory(bash(r.dir, workflowsGuardScript(r.base)))).toEqual([])
    expect(r.git('diff', '--cached', '--name-only', r.base)).toBe('apps/web/src/a.ts')
  })

  it('names a merge that brings a workflow change in; an unknown base checks the staged change alone', () => {
    const r = repo({ [CI]: 'name: CI\n' })
    const main = r.git('rev-parse', '--abbrev-ref', 'HEAD')
    r.git('checkout', '-qb', 'session/x')
    r.put('apps/web/src/a.ts', 'export {}\n')
    const head = r.commit('work')
    r.git('checkout', '-q', main)
    r.put(CI, 'name: CI upstream\n')
    r.commit('upstream ci')
    r.git('checkout', '-q', 'session/x')
    r.git('-c', 'user.email=t@t', 'merge', '-q', '--no-edit', main)
    expect(guard(r.dir, head)).toEqual([CI])
    expect(guard(r.dir, 'f'.repeat(40))).toEqual([])
    expect(guard(r.dir, null)).toEqual([])
  })
})
