/**
 * The two halves of an OBSERVED compatibility check (D31): what the kit provides, and what a
 * plugin uses.
 *
 * The machinery this replaces asked a plugin to PREDICT its compatibility — `requires.kit` as a
 * semver range, `requires.pluginApi` as an integer — and a prediction goes stale the moment either
 * side moves without the other noticing. Both numbers are written by a person, checked by a
 * matcher, and wrong silently. What is measurable instead:
 *
 *   1. the kit EMITS a ledger of what it provides (`docs/plugin-api.md`, `## Surface ledger`,
 *      generated by `scripts/plugin-api-doc.mjs`);
 *   2. a plugin's USE is a derived fact — the symbols its own files import from a declared entry;
 *   3. compatibility is `uses \ ledger`, a set difference over strings.
 *
 * A set difference is the whole point. It is deterministic, it has no grammar to get wrong, and
 * **it cannot throw** — where a malformed semver range throws out of the matcher and arrives at the
 * caller as a generic failure with nothing to act on, which is the exact shape of bug that made
 * every pin a guess. Whatever is missing names itself, and carries the replacement import when one
 * is knowable.
 *
 * Pure apart from reading files, and nothing runs at import time, so
 * `apps/web/tests/config/surface.test.ts` drives every function with fixtures as well as over the
 * real repository. `surface.d.mts` beside this file is the hand-written type surface (no `allowJs`).
 *
 * **The one non-`node:` dependency, and why it is lazy.** Reading which symbols a file imports is a
 * parse, not a regex: `import { a as b, type c }` and `export { d } from` are four shapes with one
 * meaning, and a regex over them is the kind of check that silently stops matching. So `usesOf`
 * uses the TypeScript compiler's own parser — loaded through `createRequire` at the point of use
 * rather than at the top of the module, so `readLedger` and `missingFrom` still work in a checkout
 * with no `node_modules`. Only the half that needs a parser needs one installed.
 */

import fs from 'node:fs'
import { createRequire } from 'node:module'
import path from 'node:path'

const require = createRequire(import.meta.url)

/** @type {import('typescript') | null} */
let cachedTs = null

/** The TypeScript parser, loaded on first use. See the module header for why this is not a top import. */
function typescript() {
  if (!cachedTs) cachedTs = require('typescript')
  return cachedTs
}

// ---------------------------------------------------------------- the declared entries

/**
 * The ledger's entries, in reading order: the server surface first, then the halves a plugin
 * reaches for less often.
 *
 * `import` is the specifier a plugin actually writes and is the ledger's KEY, so it is the thing
 * both the generator and this module have to agree on — which is why the list lives here and
 * `scripts/plugin-api-doc.mjs` reads it rather than keeping a second copy. The repo path beside it
 * is how an import is resolved back to an entry; a reader never sees it.
 *
 * The CLI entries are spelled as prose because a plugin's CLI half lives beside them and there is
 * no alias for that package — the label is what appears in the ledger, so it has to be stable
 * whatever it looks like.
 */
export const LEDGER_ENTRIES = [
  { import: '@/plugins/api', file: 'apps/web/src/plugins/api/index.ts' },
  { import: '@/plugins/api/peers', file: 'apps/web/src/plugins/api/peers.ts' },
  { import: '@/plugins/api/ui-wiring', file: 'apps/web/src/plugins/api/ui-wiring.ts' },
  { import: '@/plugins/api/ui', file: 'apps/web/src/plugins/api/ui.ts' },
  { import: '@/plugins/types', file: 'apps/web/src/plugins/types.ts' },
  { import: '@/db/schema/kit', file: 'apps/web/src/db/schema/kit.ts' },
  { import: '@launch/shared/plugins/api', file: 'packages/shared/src/plugins/api.ts' },
  { import: "'../api' (apps/cli/src/plugins/api.ts)", file: 'apps/cli/src/plugins/api.ts' },
  { import: "'./types' (apps/cli/src/plugins/types.ts)", file: 'apps/cli/src/plugins/types.ts' },
  { import: '@testkit/integration', file: 'apps/web/tests/kit/integration.ts' },
  { import: '@testkit/unit', file: 'apps/web/tests/kit/unit.ts' },
]

/** Where a plugin's three trees live, by package. */
export const PLUGIN_ROOTS = [
  'apps/web/src/plugins/',
  'packages/shared/src/plugins/',
  'apps/cli/src/plugins/',
]

/**
 * Where a plugin may import the host from. Resolved repo paths, so `@/x`, `../../x` and
 * `@launch/shared/x` all land in the same vocabulary.
 *
 * Wider than `LEDGER_ENTRIES` on purpose: the whole of `packages/shared/src` is importable by a
 * plugin's contract module, while only two of its files are LEDGERED. That gap is the honest
 * boundary of this method rather than a hole in it — see `usesOf`.
 */
export const DECLARED_ENTRIES = [
  // The server surface and the context family, plus the two UI halves and the peer escape hatches.
  'apps/web/src/plugins/api',
  // `ServerPlugin` / `UiPlugin` themselves.
  'apps/web/src/plugins/types',
  // The build-time schema symbols, which cannot be injected: a `pgTable(...)` runs at module scope.
  'apps/web/src/db/schema/kit',
  // The CLI half.
  'apps/cli/src/plugins/api',
  'apps/cli/src/plugins/types',
  // The TEST kit: `@testkit/integration` is the harness (a real database, the real app, the real
  // provider tree), `@testkit/unit` the context builders. A plugin's tests were out of scope for
  // this rule only because there was nowhere to point them; there is now.
  'apps/web/tests/kit',
  // Every shared contract module — the package is the contract, and a plugin's own schemas are
  // built out of it.
  'packages/shared/src',
]

/**
 * Names a plugin may not take as its id.
 *
 * Most are barrel FILENAMES: `plugins/ui.ts` and `plugins/ui/index.ts` would otherwise be two
 * different things spelled the same way in an import. `api` is the plugin API directory
 * (`plugins/api/**`), which is a host surface rather than a plugin and must classify as one —
 * without this, every core import of `@/plugins/api` would read as reaching into a plugin called
 * "api", and the directory would be reported as an installed plugin with no declared surface.
 */
export const RESERVED_PLUGIN_IDS = new Set([
  'index',
  'server',
  'ui',
  'schema',
  'types',
  'api',
  'worker-exports',
])

// ---------------------------------------------------------------- paths and specifiers

/** Drop the extension and a trailing `/index`, so the four entry spellings normalise to one. */
export function normaliseModulePath(p) {
  return p.replace(/\.(tsx?|jsx?)$/, '').replace(/\/index$/, '')
}

/** The plugin id a repo-relative path belongs to, or null when it is not inside a plugin. */
export function pluginIdOfPath(repoPath) {
  for (const root of PLUGIN_ROOTS) {
    if (!repoPath.startsWith(root)) continue
    const rest = repoPath.slice(root.length)
    const id = (rest.split('/')[0] ?? '').replace(/\.(tsx?|jsx?)$/, '')
    // The barrel files themselves belong to no plugin — and a specifier may arrive without an
    // extension (`./plugins/index`), so the name has to be checked, not just the dot.
    if (id === '' || id.includes('.') || RESERVED_PLUGIN_IDS.has(id)) return null
    return id
  }
  return null
}

/**
 * `@/x` → `apps/web/src/x`; `@launch/shared/x` → `packages/shared/src/x`;
 * `@testkit/x` → `apps/web/tests/kit/x`; else relative. A bare third-party specifier is null.
 *
 * `@testkit` is resolved rather than left as an unknown bare specifier, which would be allowed by
 * accident. Mapping it makes it a DECLARED entry like the others.
 */
export function resolveSpecifier(importer, specifier) {
  if (specifier === '@testkit') return 'apps/web/tests/kit'
  if (specifier.startsWith('@testkit/'))
    return `apps/web/tests/kit/${specifier.slice('@testkit/'.length)}`
  if (specifier.startsWith('@/')) return `apps/web/src/${specifier.slice(2)}`
  if (specifier.startsWith('@launch/shared/'))
    return `packages/shared/src/${specifier.slice('@launch/shared/'.length)}`
  if (specifier.startsWith('.'))
    return path.posix.normalize(path.posix.join(path.posix.dirname(importer), specifier))
  return null
}

/**
 * The ledger entry a resolved module path IS, or null.
 *
 * An exact match on the normalised path, never a prefix: `@/plugins/api/peers` is its own entry
 * beside `@/plugins/api`, and a prefix rule would fold the two together and report every peer
 * symbol as missing from the barrel.
 */
export function ledgerEntryOfModule(modulePath) {
  if (!modulePath) return null
  const normalised = normaliseModulePath(modulePath)
  for (const entry of LEDGER_ENTRIES) {
    if (normaliseModulePath(entry.file) === normalised) return entry.import
  }
  return null
}

/**
 * The edit, per kit module a plugin used to reach for.
 *
 * **Every diagnostic carries its replacement**, because installs are performed by agents and a
 * message that says only what is wrong gives one nothing to do. Longest prefix wins, so a whole
 * directory can be answered once and a particular module inside it more precisely.
 */
export const SUGGESTED_ENTRY = [
  ['apps/web/src/db/schema/rls', "import { tenantIsolation } from '@/db/schema/kit'"],
  ['apps/web/src/db/schema/_helpers', "import { tenantRef, timestamps } from '@/db/schema/kit'"],
  ['apps/web/src/db/schema/tenants', "import { tenants } from '@/db/schema/kit'"],
  ['apps/web/src/db/schema/users', "import { users } from '@/db/schema/kit'"],
  ['apps/web/src/db/schema/groups', "import { groups } from '@/db/schema/kit'"],
  [
    'apps/web/src/db/schema',
    "import { tenantRef, timestamps, tenantIsolation, tenants, users } from '@/db/schema/kit' — for a row TYPE, import type { Tenant } from '@/plugins/api'; for the whole merged namespace, allTables() from '@/plugins/api/peers'",
  ],
  [
    'apps/web/src/db/client',
    "the handle is ctx.db; for a signature, import type { Database } from '@/plugins/api'",
  ],
  [
    'apps/web/src/config',
    "the value is ctx.config; for a signature, import type { PluginConfig } from '@/plugins/api'",
  ],
  [
    'apps/web/src/api/utils/core/logger',
    "the value is ctx.logger; for a signature, import type { Logger } from '@/plugins/api'",
  ],
  [
    'apps/web/src/api/utils/core/errors',
    'throw through the context: ctx.notFound(…), ctx.forbidden(…), ctx.conflict(…)',
  ],
  [
    'apps/web/src/api/utils/routes/route-helpers',
    "const ctx = requestCtx(c) — import { requestCtx } from '@/plugins/api'",
  ],
  ['apps/web/src/api/utils/routes/router', "import { createRouter } from '@/plugins/api'"],
  ['apps/web/src/api/utils/routes/validate', "import { validate } from '@/plugins/api'"],
  [
    'apps/web/src/api/utils/routes/pagination',
    "ctx.page(items, total, query) — or import { pageWindow } from '@/plugins/api'",
  ],
  [
    'apps/web/src/api/middleware/permissions',
    'ctx.guard(action, subject) / ctx.can(action, subject)',
  ],
  ['apps/web/src/api/middleware/feature', "import { requireFeature } from '@/plugins/api'"],
  ['apps/web/src/api/services/jobs', 'ctx.enqueue(input) — the binding is already bound'],
  [
    'apps/web/src/api/services/realtime',
    "ctx.nudge(entity, id) — or import { realtimeEvent, nudge } from '@/plugins/api'",
  ],
  ['apps/web/src/api/services/notifications', "import { notify, notifyMany } from '@/plugins/api'"],
  ['apps/web/src/api/services/activity', "import { recordActivity } from '@/plugins/api'"],
  [
    'apps/web/src/api/services/storage',
    'ctx.storage() — 503 storage_not_configured without the binding',
  ],
  [
    'apps/web/src/api/services/access',
    "import { sharedWithMyGroups } from '@/plugins/api'; the scope is ctx.scope",
  ],
  [
    'apps/web/src/api/services/ai/kit',
    "import { defineTool } from '@/plugins/api'; the loop is ctx.toolLoop(…)",
  ],
  [
    'apps/web/src/api/services/ai',
    "import { recordUsage, AiNotConfiguredError } from '@/plugins/api'",
  ],
  ['apps/web/src/api/services/agents', "import { toolCtx, agentCtx } from '@/plugins/api'"],
  [
    'apps/web/src/api/observability',
    "import { withAgentTrace, traceChatClient } from '@/plugins/api'; the tracer is on the context",
  ],
  [
    'apps/web/src/api/queues/jobs',
    "const ctx = jobCtx(raw) — import { jobCtx } from '@/plugins/api'",
  ],
  [
    'apps/web/src/api/scheduled',
    "const ctx = cronCtx(raw) — import { cronCtx } from '@/plugins/api'",
  ],
  ['apps/web/src/api/workflows', "import { workflowCtx } from '@/plugins/api'"],
  ['apps/web/src/api/types', "import type { PluginBindings } from '@/plugins/api'"],
  [
    'apps/web/src/plugins/server',
    "import { extensions } from '@/plugins/api/peers' — never the barrel",
  ],
  [
    'apps/web/src/plugins/schema',
    "import { allTables } from '@/plugins/api/peers' — never the barrel",
  ],
  ['apps/web/src/ui/components/SideNav', "import type { NavItem } from '@/plugins/api/ui-wiring'"],
  ['apps/web/src/ui/hooks/useNavGuard', "import { useNavGuard } from '@/plugins/api/ui-wiring'"],
  ['apps/web/src/ui/lib/feature-guards', "import { featureGuard } from '@/plugins/api/ui-wiring'"],
  ['apps/web/src/ui/pages/Home', "import type { QuickLink } from '@/plugins/api/ui-wiring'"],
  ['apps/web/src/ui/components/shared', "import { … } from '@/plugins/api/ui' (a lazy page only)"],
  ['apps/web/src/ui/components', "import { … } from '@/plugins/api/ui' (a lazy page only)"],
  ['apps/web/src/ui/lib/api-client', "import { api } from '@/plugins/api/ui'"],
  ['apps/web/src/ui/lib/format', "import { formatDate } from '@/plugins/api/ui'"],
  ['apps/web/src/ui/hooks', "import { useAuth, usePermissions } from '@/plugins/api/ui'"],
  // The test harness. Longest prefix wins, so the particular modules answer before the catch-all.
  [
    'apps/web/tests/helpers/auth',
    "import { createTestUser, createTestTenantWithUser, createTestSession, sessionCookieHeader } from '@testkit/integration'",
  ],
  ['apps/web/tests/helpers/db', "import { setupTestDatabase } from '@testkit/integration'"],
  ['apps/web/tests/helpers/request', "import { request, json } from '@testkit/integration'"],
  ['apps/web/tests/mocks/bindings', "import { createTestEnv, stubs } from '@testkit/integration'"],
  [
    'apps/web/tests/ui/helpers/renderWithProviders',
    "import { renderWithProviders, makeSession, makeUser, rulesFor } from '@testkit/integration'",
  ],
  [
    'apps/web/tests',
    "the harness is '@testkit/integration'; a context builder (makeRequestCtx, makeJobCtx, makeToolCtx…) is '@testkit/unit'",
  ],
  ['apps/cli/src/context', "import { requireClient } from '../api'"],
  ['apps/cli/src/api', "import { CliApiError } from '../api'"],
  ['apps/cli/src/errors', "import { CliError } from '../api'"],
  ['apps/cli/src/utils/output', "import { renderTable, formatPagination } from '../api'"],
]

/** The replacement import for a resolved kit module, longest prefix first, else the catch-all. */
export function suggestionFor(target) {
  let best
  for (const entry of SUGGESTED_ENTRY) {
    if (target === entry[0] || target.startsWith(`${entry[0]}/`)) {
      if (!best || entry[0].length > best[0].length) best = entry
    }
  }
  return best ? best[1] : "reach the host through '@/plugins/api' (or '@/plugins/api/ui' in a page)"
}

// ---------------------------------------------------------------- reading imports

/**
 * Every static import and re-export of a TypeScript source, with the NAMES it binds.
 *
 * One parse rather than a regex, because the shapes that mean "this file uses that symbol" are
 * `import { a }`, `import { a as b }`, `import { type a }`, `import type { a }` and
 * `export { a } from` — and a regex over those is a check that stops matching without saying so.
 *
 * `propertyName ?? name` is the EXPORTED name: `import { a as b }` uses `a`, which is what the
 * ledger records. **Type-only imports count**, declaration-level and specifier-level alike:
 * removing a type from the surface breaks a plugin exactly as a value does, it just breaks at
 * compile time.
 *
 * A namespace import (`import * as x`) binds no names this can attribute, so it records none and
 * says so with `namespace: true` — a limit of the method, not a claim that nothing is used.
 */
export function moduleImports(source, fileName = 'x.ts') {
  const ts = typescript()
  const file = ts.createSourceFile(fileName, source, ts.ScriptTarget.Latest, true)
  const out = []
  const visit = node => {
    if (
      (ts.isImportDeclaration(node) || ts.isExportDeclaration(node)) &&
      node.moduleSpecifier &&
      ts.isStringLiteral(node.moduleSpecifier)
    ) {
      const isImport = ts.isImportDeclaration(node)
      const clause = isImport ? node.importClause : null
      const typeOnly = isImport ? Boolean(clause?.isTypeOnly) : node.isTypeOnly
      const bindings = isImport ? clause?.namedBindings : node.exportClause
      const names = []
      let namespace = false
      if (bindings && ts.isNamespaceImport(bindings)) namespace = true
      else if (bindings && (ts.isNamedImports(bindings) || ts.isNamedExports(bindings))) {
        for (const element of bindings.elements) {
          names.push((element.propertyName ?? element.name).text)
        }
      }
      const { line } = file.getLineAndCharacterOfPosition(node.getStart(file))
      out.push({ specifier: node.moduleSpecifier.text, names, namespace, typeOnly, line: line + 1 })
    }
    ts.forEachChild(node, visit)
  }
  visit(file)
  return out
}

/** Static import/export specifiers of a TypeScript source, with whether the import is type-only. */
export function staticImports(source) {
  return moduleImports(source).map(({ specifier, typeOnly, line }) => ({
    specifier,
    typeOnly,
    line,
  }))
}

// ---------------------------------------------------------------- the ledger

const LEDGER_HEADING = '## Surface ledger'
const LEDGER_FENCE = '```text'

/**
 * The kit's ledger, from `docs/plugin-api.md`, or **null when there is nothing to read**.
 *
 * Null rather than a throw for three separate absences — no file, no `## Surface ledger` section,
 * no fenced block under it — because every one of them is a legitimate state of somebody's
 * checkout: a copy of the kit made before the ledger existed, a doc deleted by an adopter, a
 * generator that has not run yet. **A caller must treat null as its own failure and say so**; what
 * it must not do is present "no ledger" as "nothing is missing", which is exactly what an empty
 * ledger would silently produce.
 *
 * Two row shapes, because the generator emits both:
 *
 *     <entry> :: <kind> :: <name> :: <signature>
 *     <entry> :: member :: <Type>.<member> :: <signature>
 *
 * They parse identically — the second is only a `kind` of `member` and a dotted `name` — which is
 * what lets `usesOf` and this agree on one key, `"<entry> :: <name>"`. A signature may itself
 * contain ` :: ` (a nested type literal can), so everything past the third separator is rejoined
 * rather than the line being split into exactly four.
 */
export function readLedger(repoRoot) {
  const file = path.join(repoRoot, 'docs/plugin-api.md')
  if (!fs.existsSync(file)) return null
  const markdown = fs.readFileSync(file, 'utf8')
  const start = markdown.indexOf(LEDGER_HEADING)
  if (start === -1) return null
  const fence = markdown.indexOf(LEDGER_FENCE, start)
  if (fence === -1) return null
  const body = markdown.slice(fence + LEDGER_FENCE.length)
  const end = body.indexOf('```')
  const members = new Map()
  for (const raw of body.slice(0, end === -1 ? undefined : end).split('\n')) {
    const parts = raw.trim().split(' :: ')
    if (parts.length < 4) continue
    const [entry, kind, name] = parts
    members.set(`${entry} :: ${name}`, {
      entry,
      kind,
      name,
      signature: parts.slice(3).join(' :: '),
    })
  }
  return {
    members,
    size: members.size,
    has: (entry, name) => members.has(`${entry} :: ${name}`),
    get: (entry, name) => members.get(`${entry} :: ${name}`),
  }
}

// ---------------------------------------------------------------- what a plugin uses

const SOURCE_FILE = /\.(tsx?|jsx?)$/

/** Every source file under `dir`, repo-relative, sorted — so the walk is deterministic. */
function sourceFilesUnder(repoRoot, dir) {
  const abs = path.join(repoRoot, dir)
  if (!fs.existsSync(abs)) return []
  const out = []
  const walk = current => {
    for (const entry of fs.readdirSync(path.join(repoRoot, current), { withFileTypes: true })) {
      const rel = `${current}/${entry.name}`
      if (entry.isDirectory()) {
        if (entry.name === 'node_modules' || entry.name === 'dist') continue
        walk(rel)
      } else if (SOURCE_FILE.test(entry.name)) out.push(rel)
    }
  }
  walk(dir.replace(/\/$/, ''))
  return out.sort()
}

/** The DECLARED entry a resolved module falls under, or null. Exact, or a directory prefix. */
export function declaredEntryOf(modulePath) {
  if (!modulePath) return null
  const normalised = normaliseModulePath(modulePath)
  for (const entry of DECLARED_ENTRIES) {
    if (normalised === entry || normalised.startsWith(`${entry}/`)) return entry
  }
  return null
}

/**
 * A repo path back to the specifier a plugin writes for it — the inverse of `resolveSpecifier`.
 *
 * Needed because `uses` is keyed by the spelling an author would recognise, and a module may be
 * reached by several (`@/db/schema/kit` and `../../../../db/schema/kit` are one key). A ledgered
 * module answers through `LEDGER_ENTRIES`, whose label is the key; this covers the rest.
 */
export function canonicalSpecifier(modulePath) {
  const ledgered = ledgerEntryOfModule(modulePath)
  if (ledgered) return ledgered
  const p = normaliseModulePath(modulePath ?? '')
  if (p === 'apps/web/tests/kit') return '@testkit'
  if (p.startsWith('apps/web/tests/kit/'))
    return `@testkit/${p.slice('apps/web/tests/kit/'.length)}`
  if (p.startsWith('apps/web/src/')) return `@/${p.slice('apps/web/src/'.length)}`
  if (p.startsWith('packages/shared/src/'))
    return `@launch/shared/${p.slice('packages/shared/src/'.length)}`
  return p === '' ? null : p
}

/**
 * What a plugin USES of the host surface: `{ [entry]: [sorted unique symbol names] }`.
 *
 * Derived, never declared. That is the whole reason this replaces a version a person types: a
 * number is a claim, and this is a measurement of the same files the compiler reads. It walks the
 * plugin's three trees AND its own tests — the tests were out of the import rule once only because
 * there was nowhere to point them, and in practice they held the worst of the coupling.
 *
 * **It records every import of a DECLARED entry, ledgered or not, and the difference from what it
 * used to do is the whole point.** Keyed by ledger entry alone, a plugin importing
 * `@launch/shared/pagination` measured as using *nothing*: the whole of `packages/shared/src`
 * is a declared entry while only one of its files is ledgered, so the import was dropped in the
 * WALK and no later reader could tell it apart from a plugin that imports nothing at all. Silently
 * losing the measurement is exactly what this machinery exists to stop, so the data is kept here
 * and the POLICY — which entries the ledger is entitled to judge — lives in `missingFrom`.
 *
 * Still ignored, because there is no host surface on the other side: imports that resolve inside
 * the plugin itself, into another plugin, or to a third-party package. Whether reaching somewhere
 * UNdeclared was allowed at all is `tests/helpers/plugins.ts`'s rule, not this measurement's.
 */
export function usesOf(repoRoot, pluginId) {
  const byEntry = new Map()
  for (const root of PLUGIN_ROOTS) {
    for (const file of sourceFilesUnder(repoRoot, `${root}${pluginId}`)) {
      const source = fs.readFileSync(path.join(repoRoot, file), 'utf8')
      for (const imported of moduleImports(source, file)) {
        const target = resolveSpecifier(file, imported.specifier)
        // Inside this plugin, or inside another one: neither is host surface.
        if (!target || pluginIdOfPath(target) !== null) continue
        if (!declaredEntryOf(target)) continue
        const entry = canonicalSpecifier(target)
        if (!entry) continue
        if (!byEntry.has(entry)) byEntry.set(entry, new Set())
        for (const name of imported.names) byEntry.get(entry).add(name)
      }
    }
  }
  // Ledger order first, then everything else alphabetically, so two runs and two readers see the
  // same document.
  const uses = {}
  const ledgerOrder = LEDGER_ENTRIES.map(e => e.import)
  const rest = [...byEntry.keys()].filter(k => !ledgerOrder.includes(k)).sort()
  for (const entry of [...ledgerOrder, ...rest]) {
    const names = byEntry.get(entry)
    if (names && names.size > 0) uses[entry] = [...names].sort((a, b) => a.localeCompare(b, 'en'))
  }
  return uses
}

/**
 * `uses \ ledger` — every symbol a plugin names that the kit no longer provides.
 *
 * The primitive the whole redesign rests on: a set difference over strings. No range to parse, no
 * comparison that can be malformed, and **no path out of here that throws**. An empty result is a
 * plugin that fits; a non-empty one names each symbol and, where it is knowable, the exact import
 * that replaces it.
 *
 * `suggestion` is the honest half. When the symbol still exists under a DIFFERENT entry it has
 * moved, and the replacement import is a fact this can compute — which is the common case, because
 * a surface is far more often reorganised than deleted. When it exists nowhere the suggestion is
 * `null`: inventing one would send the reader to a name that is not there, which is worse than
 * saying nothing (the same reason the capability index is checked rather than hand-maintained).
 *
 * **A null ledger yields an empty list, and the caller owns that.** This function cannot
 * distinguish "nothing is missing" from "there was nothing to compare against", so a caller that
 * treats null as a pass has disabled its own check — `readLedger` says why it may be null.
 */
export function missingFrom(uses, ledger) {
  if (!ledger) return []
  const elsewhere = new Map()
  // Which entries this ledger is entitled to judge. Derived from the ledger itself rather than
  // from a second list, so an entry that stops being emitted stops being judged in the same
  // breath. This is the policy `usesOf` deliberately does NOT apply: the whole of
  // `packages/shared/src` is importable while only part of it is ledgered, and a key with no
  // ledger side would report every symbol under it as missing — a flood that says nothing.
  const covered = new Set()
  for (const member of ledger.members.values()) {
    covered.add(member.entry)
    if (!elsewhere.has(member.name)) elsewhere.set(member.name, member.entry)
  }
  const missing = []
  for (const [entry, names] of Object.entries(uses ?? {})) {
    if (!covered.has(entry)) continue
    for (const symbol of names) {
      if (ledger.has(entry, symbol)) continue
      const moved = elsewhere.get(symbol)
      missing.push({
        entry,
        symbol,
        suggestion: moved ? `import { ${symbol} } from '${moved}'` : null,
      })
    }
  }
  return missing
}
