name = "rfspike-app-staging"
main = "src/index.js"
compatibility_date = "2026-09-01"
compatibility_flags = ["nodejs_compat"]
workers_dev = false

[assets]
directory = "./public"
binding = "ASSETS"

[[kv_namespaces]]
binding = "RATE_LIMIT_KV"
id = "708597ddb2ab4ec3a05028334b9e9624"
