/**
 * Row-level security scaffolding (D1). Ships INERT: policies are generated by drizzle-kit from
 * `tenantIsolation()` on every tenant table and target the `launch_app` role, which
 * `scripts/db-roles.ts` creates NOLOGIN. Nothing connects as that role until
 * `TENANT_SCOPE_MODE=enforce` is promoted after the spike in docs/RLS.md.
 *
 * Ported from the Node reference app's `src/db/schema/rls.ts`; only the role name and table lists changed.
 */
import { sql } from 'drizzle-orm'
import { pgPolicy } from 'drizzle-orm/pg-core'

/**
 * The least-privileged database role the tenant-scoped request path would connect as.
 * Created (with grants) by `scripts/db-roles.ts` — NOT by drizzle-kit, which is why
 * `entities: { roles: true }` must stay OFF in `drizzle.config.ts`.
 */
export const APP_ROLE = 'launch_app'

/**
 * The active tenant, read from the transaction-local GUC that `withTenantScope` sets.
 *
 * Unset (or empty) → NULL → `tenant_id = NULL` is NULL → no row passes: nothing is
 * readable and nothing is writable. That is the safe default, not a fail-open one.
 */
const TENANT_GUC = sql`nullif(current_setting('app.tenant_id', true), '')::uuid`

/**
 * ONE policy predicate, shared by every table. Do not inline a copy per table: drizzle-kit
 * diffs the rendered SQL text, so a stray space shows up as N spurious `ALTER POLICY`
 * statements in the next migration.
 *
 * `USING` filters reads (and the pre-image of updates/deletes); `WITH CHECK` rejects writing
 * a row belonging to another tenant with a `42501` error.
 *
 * Deliberately no `FORCE ROW LEVEL SECURITY`: the table owner (what the Worker connects as)
 * keeps bypassing these policies, which is what lets pre-tenant auth paths work and what
 * makes the rollout reversible by config alone.
 *
 * @param table  table name, used only to name the policy
 * @param column the column holding the tenant id — `tenant_id` everywhere except
 *               `tenants` itself, which is policied on its own primary key
 */
export function tenantIsolation(table: string, column = sql`tenant_id`) {
  return pgPolicy(`${table}_tenant_isolation`, {
    as: 'permissive',
    for: 'all',
    to: APP_ROLE,
    using: sql`${column} = ${TENANT_GUC}`,
    withCheck: sql`${column} = ${TENANT_GUC}`,
  })
}

/**
 * `users` has no `tenant_id` — a user is global and belongs to MANY tenants through
 * `tenant_users` — so it is scoped by MEMBERSHIP of the active tenant instead.
 *
 * `WITH CHECK` is the same predicate: a user row can only be written by a connection scoped
 * to a tenant the user is already a member of. Creating a user is therefore impossible on a
 * scoped connection — deliberately: every path that does so (invite accept, login flows) is
 * pre-tenant by nature and runs on the owner connection, which bypasses RLS.
 *
 * Invariant the kit must keep: every person a tenant can see has a `tenant_users` row
 * (invitations insert membership before anything else references the user).
 *
 * No recursion: `tenant_users`' own policy filters on `tenant_id` and never looks at `users`.
 */
export function membershipIsolation() {
  const predicate = sql`id in (select user_id from tenant_users where tenant_id = ${TENANT_GUC})`
  return pgPolicy('users_tenant_isolation', {
    as: 'permissive',
    for: 'all',
    to: APP_ROLE,
    using: predicate,
    withCheck: predicate,
  })
}

/**
 * Tables the app role must never touch at all — `scripts/db-roles.ts` REVOKEs them, which is
 * strictly stronger than a policy. They are pre-tenant / cross-tenant infrastructure written
 * by the auth paths through the owner connection, so a tenant-scoped connection cannot read
 * another tenant's sessions or OAuth tokens even if a policy were ever missed.
 *
 * `db-roles.ts` only REVOKEs the ones that exist (grants phase runs after migrations).
 */
export const RLS_REVOKED_TABLES = [
  'user_sessions',
  'magic_link_tokens',
  'oauth_providers',
  'access_requests',
] as const

/**
 * Deliberately NOT policied — every exclusion is a decision recorded here rather than hidden
 * by omission. `tests/api/rls-coverage.test.ts` asserts the unpolicied set in the live catalog
 * equals exactly this list, and that none of these tables has a `tenant_id` column (one that did
 * would need a policy). Add a table here only with a reason.
 *
 * The revoked tables are excluded because a REVOKE is stronger than a policy. `feature_flags` is
 * excluded for a different reason and is NOT revoked: it is platform-level rollout state with no
 * tenant column at all, readable by the app role on every request (D30). Its per-tenant companion,
 * `tenant_feature_overrides`, is policied like any other tenant table.
 */
export const RLS_EXCLUDED_TABLES = [...RLS_REVOKED_TABLES, 'feature_flags'] as const

/**
 * An installed plugin declares ITS unpolicied tables through `ServerPlugin.rlsExcludedTables`
 * (D31), and `tests/api/rls-coverage.test.ts` unions the two — deliberately NOT here. This module
 * is imported by every schema file and by `drizzle.config.ts`; reading the server barrel from it
 * would close the cycle `rls.ts → plugins/server.ts → <plugin>/index.ts → db/schema → rls.ts`, and
 * the list above is built at module scope, so the loser of that race reads `undefined`. The list
 * has exactly one consumer, and unioning at the consumer costs nothing.
 */
